part of coin;


List<Coin> CryptsyCoins = <Coin> [
  BitCoin,
  USDollar,
  Dogecoin,
  DarkCoin,
  FeatherCoin,
  LiteCoin,
  ReddCoin$Cryptsy,
  FourtyTwoCoin,
  AsiaCoin,
  Aegis,
  AlphaCoin,
  AlienCoin,
  AmericanCoin,
  AnonCoin,
  ApexCoin,
  Argentum,
  AuroraCoin,
  BlackCoin,
  BattleCoin,
  Benjamins,
  Betacoin,
  BlueCoin,
  BBQCoin,
  BitBar,
  BitcoinDark,
  ByteCoin$Cryptsy,
  BitGem,
  CryptoBuck,
  CACHeCoin,
  CAIx,
  BottleCaps,
  CashCoin,
  CatCoin,
  CryptogenicBullion,
  CinniCoin,
  CloakCoin,
  CopperLark,
  Cosmoscoin,
  CHNCoin,
  ConcealCoin,
  CommunityCoin,
  CoolCoin,
  CraftCoin,
  CryptCoin,
  CasinoCoin,
  eMark,
  Digibyte,
  DigitalCoin,
  Diamond,
  DarkCash,
  DevCoin,
  EarthCoin,
  ElaCoin,
  Einsteinium,
  Emerald,
  ExeCoin,
  EZCoin,
  FireflyCoin,
  FlutterCoin,
  FractalCoin,
  FreiCoin,
  Franko,
  FastCoin,
  GrandCoin,
  Globalcoin,
  GoldCoin,
  Galaxycoin,
  GlyphCoin,
  GuerillaCoin,
  HoboNickels,
  HunterCoin,
  HeavyCoin,
  IcebergCoin,
  InfiniteCoin,
  IOCoin,
  IXCoin,
  JunkCoin,
  JudgeCoin,
  KlondikeCoin,
  KeyCoin,
  KrugerCoin,
  LegendaryCoin,
  Lucky7Coin,
  LuckyCoin,
  LiteBar,
  LiteCoinX,
  LycanCoin,
  MaxCoin,
  MegaCoin,
  Minerals,
  MintCoin,
  MiningContract1,
  MiningContract2,
  MinCoin,
  MurrayCoin,
  MyriadCoin,
  MazaCoin,
  NanoToken,
  NautilusCoin,
  NavajoCoin,
  Nibble,
  NeoCoin,
  Netcoin,
  NameCoin,
  NobleCoin,
  NoirBits,
  NoirShares,
  NovaCoin,
  Nxt,
  NyanCoin,
  Orbitcoin,
  OpenSourceCoin,
  PhilosopherStone,
  CryptsyPoints,
  PotCoin,
  Peercoin,
  PseudoCoin,
  BitsharesPTS,
  PhoenixCoin,
  PayCoin,
  Quark,
  RonPaulCoin,
  RotoCoin,
  RoyalCoin,
  Razor,
  SaturnCoinV2,
  StableCoin,
  SilkCoin$Cryptsy,
  SaffronCoin,
  ShieldCoin,
  SmartCoin,
  SpainCoin,
  Spots,
  SecureCoin,
  StarCoin,
  SuperCoin,
  SexCoin,
  Sync,
  TagCoin,
  TakCoin,
  TekCoin,
  TeslaCoin,
  TigerCoin,
  TorCoin,
  TerraCoin,
  UnbreakableCoin,
  Unobtanium,
  URO,
  USDe$Cryptsy,
  UltraCoin,
  ViaCoin,
  VootCoin,
  VeriCoin,
  VertCoin,
  WhiteCoin,
  WorldCoin,
  X11Coin,
  JouleCoin,
  LibertyCoin,
  PrimeCoin,
  XXXCoin,
  YaCoin,
  YBCoin,
  ZcCoin,
  ZedCoin,
  ZetaCoin,
  AndroidsTokensV2,
  AsicCoin,
  BatCoin,
  ColossusCoin,
  CopperBars,
  Continuumcoin,
  Doubloons,
  DimeCoin,
  DamaCoin,
  ElephantCoin,
  FlappyCoin,
  FlorinCoin,
  GameCoin,
  KarmaCoin,
  LeafCoin,
  LottoCoin,
  MemeCoin,
  KittehCoin,
  MoonCoin,
  MasterCoinHydro,
  RabbitCoin,
  RedCoin,
  FedoraCoin,
  Tickets,
  XenCoin,
  ZeitCoin
];

Map<Pair, String> CryptsyIds = <Pair, String> {
  BitCoin_USDollar: '2',
  Dogecoin_USDollar: '182',
  DarkCoin_USDollar: '213',
  FeatherCoin_USDollar: '6',
  LiteCoin_USDollar: '1',
  ReddCoin$Cryptsy_USDollar: '262',
  FourtyTwoCoin_BitCoin: '141',
  AsiaCoin_BitCoin: '199',
  Aegis_BitCoin: '253',
  AlphaCoin_BitCoin: '57',
  AlienCoin_BitCoin: '273',
  AmericanCoin_BitCoin: '43',
  AnonCoin_BitCoin: '66',
  ApexCoin_BitCoin: '257',
  Argentum_BitCoin: '48',
  AuroraCoin_BitCoin: '160',
  BlackCoin_BitCoin: '179',
  BattleCoin_BitCoin: '142',
  Benjamins_BitCoin: '157',
  Betacoin_BitCoin: '129',
  BlueCoin_BitCoin: '251',
  BBQCoin_BitCoin: '10',
  BitBar_BitCoin: '23',
  BitcoinDark_BitCoin: '256',
  ByteCoin$Cryptsy_BitCoin: '49',
  BitGem_BitCoin: '50',
  CryptoBuck_BitCoin: '102',
  CACHeCoin_BitCoin: '154',
  CAIx_BitCoin: '221',
  BottleCaps_BitCoin: '53',
  CashCoin_BitCoin: '150',
  CatCoin_BitCoin: '136',
  CryptogenicBullion_BitCoin: '70',
  CinniCoin_BitCoin: '197',
  CloakCoin_BitCoin: '227',
  CopperLark_BitCoin: '95',
  Cosmoscoin_BitCoin: '74',
  CHNCoin_BitCoin: '8',
  ConcealCoin_BitCoin: '260',
  CommunityCoin_BitCoin: '198',
  CoolCoin_BitCoin: '266',
  CraftCoin_BitCoin: '58',
  CryptCoin_BitCoin: '219',
  CasinoCoin_BitCoin: '68',
  eMark_BitCoin: '131',
  Digibyte_BitCoin: '167',
  DigitalCoin_BitCoin: '26',
  Diamond_BitCoin: '72',
  Dogecoin_BitCoin: '132',
  DarkCoin_BitCoin: '155',
  DarkCash_BitCoin: '274',
  DevCoin_BitCoin: '40',
  EarthCoin_BitCoin: '139',
  ElaCoin_BitCoin: '12',
  Einsteinium_BitCoin: '188',
  Emerald_BitCoin: '69',
  ExeCoin_BitCoin: '183',
  EZCoin_BitCoin: '47',
  FireflyCoin_BitCoin: '138',
  FlutterCoin_BitCoin: '192',
  FractalCoin_BitCoin: '259',
  FreiCoin_BitCoin: '39',
  Franko_BitCoin: '33',
  FastCoin_BitCoin: '44',
  FeatherCoin_BitCoin: '5',
  GrandCoin_BitCoin: '82',
  Globalcoin_BitCoin: '76',
  GoldCoin_BitCoin: '30',
  Galaxycoin_BitCoin: '78',
  GlyphCoin_BitCoin: '229',
  GuerillaCoin_BitCoin: '241',
  HoboNickels_BitCoin: '80',
  HunterCoin_BitCoin: '249',
  HeavyCoin_BitCoin: '185',
  IcebergCoin_BitCoin: '267',
  InfiniteCoin_BitCoin: '59',
  IOCoin_BitCoin: '272',
  IXCoin_BitCoin: '38',
  JunkCoin_BitCoin: '25',
  JudgeCoin_BitCoin: '269',
  KlondikeCoin_BitCoin: '178',
  KeyCoin_BitCoin: '255',
  KrugerCoin_BitCoin: '65',
  LegendaryCoin_BitCoin: '204',
  Lucky7Coin_BitCoin: '116',
  LuckyCoin_BitCoin: '34',
  LiteBar_BitCoin: '202',
  LiteCoin_BitCoin: '3',
  LiteCoinX_BitCoin: '233',
  LycanCoin_BitCoin: '177',
  MaxCoin_BitCoin: '152',
  MegaCoin_BitCoin: '45',
  Minerals_BitCoin: '258',
  MintCoin_BitCoin: '156',
  MiningContract1_BitCoin: '187',
  MiningContract2_BitCoin: '196',
  MinCoin_BitCoin: '7',
  MurrayCoin_BitCoin: '189',
  MyriadCoin_BitCoin: '200',
  MazaCoin_BitCoin: '164',
  NanoToken_BitCoin: '64',
  NautilusCoin_BitCoin: '207',
  NavajoCoin_BitCoin: '252',
  Nibble_BitCoin: '32',
  NeoCoin_BitCoin: '90',
  Netcoin_BitCoin: '134',
  NameCoin_BitCoin: '29',
  NobleCoin_BitCoin: '264',
  NoirBits_BitCoin: '54',
  NoirShares_BitCoin: '211',
  NovaCoin_BitCoin: '13',
  Nxt_BitCoin: '159',
  NyanCoin_BitCoin: '184',
  Orbitcoin_BitCoin: '75',
  OpenSourceCoin_BitCoin: '144',
  PhilosopherStone_BitCoin: '86',
  CryptsyPoints_BitCoin: '120',
  PotCoin_BitCoin: '173',
  Peercoin_BitCoin: '28',
  PseudoCoin_BitCoin: '268',
  BitsharesPTS_BitCoin: '119',
  PhoenixCoin_BitCoin: '31',
  PayCoin_BitCoin: '92',
  Quark_BitCoin: '71',
  ReddCoin$Cryptsy_BitCoin: '169',
  RonPaulCoin_BitCoin: '143',
  RotoCoin_BitCoin: '235',
  RoyalCoin_BitCoin: '9',
  Razor_BitCoin: '237',
  SaturnCoinV2_BitCoin: '232',
  StableCoin_BitCoin: '51',
  SilkCoin$Cryptsy_BitCoin: '225',
  SaffronCoin_BitCoin: '270',
  ShieldCoin_BitCoin: '248',
  SmartCoin_BitCoin: '158',
  SpainCoin_BitCoin: '180',
  Spots_BitCoin: '81',
  SecureCoin_BitCoin: '88',
  StarCoin_BitCoin: '83',
  SuperCoin_BitCoin: '239',
  SexCoin_BitCoin: '153',
  Sync_BitCoin: '271',
  TagCoin_BitCoin: '117',
  TakCoin_BitCoin: '166',
  TekCoin_BitCoin: '114',
  TeslaCoin_BitCoin: '223',
  TigerCoin_BitCoin: '130',
  TorCoin_BitCoin: '250',
  TerraCoin_BitCoin: '27',
  UnbreakableCoin_BitCoin: '203',
  Unobtanium_BitCoin: '133',
  URO_BitCoin: '247',
  USDe$Cryptsy_BitCoin: '201',
  UltraCoin_BitCoin: '163',
  ViaCoin_BitCoin: '261',
  VootCoin_BitCoin: '254',
  VeriCoin_BitCoin: '209',
  VertCoin_BitCoin: '151',
  WhiteCoin_BitCoin: '195',
  WorldCoin_BitCoin: '14',
  X11Coin_BitCoin: '210',
  JouleCoin_BitCoin: '115',
  LibertyCoin_BitCoin: '208',
  PrimeCoin_BitCoin: '63',
  XXXCoin_BitCoin: '265',
  YaCoin_BitCoin: '11',
  YBCoin_BitCoin: '73',
  ZcCoin_BitCoin: '140',
  ZedCoin_BitCoin: '170',
  ZetaCoin_BitCoin: '85',
  AndroidsTokensV2_LiteCoin: '94',
  AnonCoin_LiteCoin: '121',
  AsicCoin_LiteCoin: '111',
  AuroraCoin_LiteCoin: '161',
  BatCoin_LiteCoin: '186',
  BlackCoin_LiteCoin: '191',
  CryptogenicBullion_LiteCoin: '123',
  CloakCoin_LiteCoin: '228',
  CHNCoin_LiteCoin: '17',
  ColossusCoin_LiteCoin: '109',
  CopperBars_LiteCoin: '91',
  CryptCoin_LiteCoin: '220',
  Continuumcoin_LiteCoin: '175',
  Doubloons_LiteCoin: '46',
  DigitalCoin_LiteCoin: '96',
  DimeCoin_LiteCoin: '206',
  DamaCoin_LiteCoin: '194',
  Dogecoin_LiteCoin: '135',
  DarkCoin_LiteCoin: '214',
  DevCoin_LiteCoin: '52',
  EarthCoin_LiteCoin: '244',
  ElephantCoin_LiteCoin: '93',
  EZCoin_LiteCoin: '55',
  FlappyCoin_LiteCoin: '246',
  FlorinCoin_LiteCoin: '61',
  Franko_LiteCoin: '171',
  FastCoin_LiteCoin: '124',
  FeatherCoin_LiteCoin: '4',
  GoldCoin_LiteCoin: '36',
  GlyphCoin_LiteCoin: '230',
  GameCoin_LiteCoin: '84',
  GuerillaCoin_LiteCoin: '242',
  InfiniteCoin_LiteCoin: '60',
  KarmaCoin_LiteCoin: '193',
  LeafCoin_LiteCoin: '245',
  LottoCoin_LiteCoin: '243',
  LiteCoinX_LiteCoin: '234',
  MaxCoin_LiteCoin: '218',
  MegaCoin_LiteCoin: '100',
  MemeCoin_LiteCoin: '56',
  KittehCoin_LiteCoin: '231',
  MoonCoin_LiteCoin: '145',
  MasterCoinHydro_LiteCoin: '62',
  Netcoin_LiteCoin: '108',
  Nxt_LiteCoin: '162',
  NyanCoin_LiteCoin: '263',
  Peercoin_LiteCoin: '125',
  PhoenixCoin_LiteCoin: '101',
  Quark_LiteCoin: '126',
  RabbitCoin_LiteCoin: '190',
  ReddCoin$Cryptsy_LiteCoin: '212',
  RedCoin_LiteCoin: '87',
  Razor_LiteCoin: '238',
  StableCoin_LiteCoin: '128',
  SuperCoin_LiteCoin: '240',
  SexCoin_LiteCoin: '98',
  TeslaCoin_LiteCoin: '224',
  FedoraCoin_LiteCoin: '147',
  Tickets_LiteCoin: '107',
  VeriCoin_LiteCoin: '215',
  VertCoin_LiteCoin: '217',
  WorldCoin_LiteCoin: '21',
  X11Coin_LiteCoin: '216',
  XenCoin_LiteCoin: '67',
  PrimeCoin_LiteCoin: '106',
  YaCoin_LiteCoin: '22',
  ZeitCoin_LiteCoin: '176',
  ZetaCoin_LiteCoin: '127'
};

List<Pair> CryptsyPairs = <Pair> [
  BitCoin_USDollar,
  Dogecoin_USDollar,
  DarkCoin_USDollar,
  FeatherCoin_USDollar,
  LiteCoin_USDollar,
  ReddCoin$Cryptsy_USDollar,
  FourtyTwoCoin_BitCoin,
  AsiaCoin_BitCoin,
  Aegis_BitCoin,
  AlphaCoin_BitCoin,
  AlienCoin_BitCoin,
  AmericanCoin_BitCoin,
  AnonCoin_BitCoin,
  ApexCoin_BitCoin,
  Argentum_BitCoin,
  AuroraCoin_BitCoin,
  BlackCoin_BitCoin,
  BattleCoin_BitCoin,
  Benjamins_BitCoin,
  Betacoin_BitCoin,
  BlueCoin_BitCoin,
  BBQCoin_BitCoin,
  BitBar_BitCoin,
  BitcoinDark_BitCoin,
  ByteCoin$Cryptsy_BitCoin,
  BitGem_BitCoin,
  CryptoBuck_BitCoin,
  CACHeCoin_BitCoin,
  CAIx_BitCoin,
  BottleCaps_BitCoin,
  CashCoin_BitCoin,
  CatCoin_BitCoin,
  CryptogenicBullion_BitCoin,
  CinniCoin_BitCoin,
  CloakCoin_BitCoin,
  CopperLark_BitCoin,
  Cosmoscoin_BitCoin,
  CHNCoin_BitCoin,
  ConcealCoin_BitCoin,
  CommunityCoin_BitCoin,
  CoolCoin_BitCoin,
  CraftCoin_BitCoin,
  CryptCoin_BitCoin,
  CasinoCoin_BitCoin,
  eMark_BitCoin,
  Digibyte_BitCoin,
  DigitalCoin_BitCoin,
  Diamond_BitCoin,
  Dogecoin_BitCoin,
  DarkCoin_BitCoin,
  DarkCash_BitCoin,
  DevCoin_BitCoin,
  EarthCoin_BitCoin,
  ElaCoin_BitCoin,
  Einsteinium_BitCoin,
  Emerald_BitCoin,
  ExeCoin_BitCoin,
  EZCoin_BitCoin,
  FireflyCoin_BitCoin,
  FlutterCoin_BitCoin,
  FractalCoin_BitCoin,
  FreiCoin_BitCoin,
  Franko_BitCoin,
  FastCoin_BitCoin,
  FeatherCoin_BitCoin,
  GrandCoin_BitCoin,
  Globalcoin_BitCoin,
  GoldCoin_BitCoin,
  Galaxycoin_BitCoin,
  GlyphCoin_BitCoin,
  GuerillaCoin_BitCoin,
  HoboNickels_BitCoin,
  HunterCoin_BitCoin,
  HeavyCoin_BitCoin,
  IcebergCoin_BitCoin,
  InfiniteCoin_BitCoin,
  IOCoin_BitCoin,
  IXCoin_BitCoin,
  JunkCoin_BitCoin,
  JudgeCoin_BitCoin,
  KlondikeCoin_BitCoin,
  KeyCoin_BitCoin,
  KrugerCoin_BitCoin,
  LegendaryCoin_BitCoin,
  Lucky7Coin_BitCoin,
  LuckyCoin_BitCoin,
  LiteBar_BitCoin,
  LiteCoin_BitCoin,
  LiteCoinX_BitCoin,
  LycanCoin_BitCoin,
  MaxCoin_BitCoin,
  MegaCoin_BitCoin,
  Minerals_BitCoin,
  MintCoin_BitCoin,
  MiningContract1_BitCoin,
  MiningContract2_BitCoin,
  MinCoin_BitCoin,
  MurrayCoin_BitCoin,
  MyriadCoin_BitCoin,
  MazaCoin_BitCoin,
  NanoToken_BitCoin,
  NautilusCoin_BitCoin,
  NavajoCoin_BitCoin,
  Nibble_BitCoin,
  NeoCoin_BitCoin,
  Netcoin_BitCoin,
  NameCoin_BitCoin,
  NobleCoin_BitCoin,
  NoirBits_BitCoin,
  NoirShares_BitCoin,
  NovaCoin_BitCoin,
  Nxt_BitCoin,
  NyanCoin_BitCoin,
  Orbitcoin_BitCoin,
  OpenSourceCoin_BitCoin,
  PhilosopherStone_BitCoin,
  CryptsyPoints_BitCoin,
  PotCoin_BitCoin,
  Peercoin_BitCoin,
  PseudoCoin_BitCoin,
  BitsharesPTS_BitCoin,
  PhoenixCoin_BitCoin,
  PayCoin_BitCoin,
  Quark_BitCoin,
  ReddCoin$Cryptsy_BitCoin,
  RonPaulCoin_BitCoin,
  RotoCoin_BitCoin,
  RoyalCoin_BitCoin,
  Razor_BitCoin,
  SaturnCoinV2_BitCoin,
  StableCoin_BitCoin,
  SilkCoin$Cryptsy_BitCoin,
  SaffronCoin_BitCoin,
  ShieldCoin_BitCoin,
  SmartCoin_BitCoin,
  SpainCoin_BitCoin,
  Spots_BitCoin,
  SecureCoin_BitCoin,
  StarCoin_BitCoin,
  SuperCoin_BitCoin,
  SexCoin_BitCoin,
  Sync_BitCoin,
  TagCoin_BitCoin,
  TakCoin_BitCoin,
  TekCoin_BitCoin,
  TeslaCoin_BitCoin,
  TigerCoin_BitCoin,
  TorCoin_BitCoin,
  TerraCoin_BitCoin,
  UnbreakableCoin_BitCoin,
  Unobtanium_BitCoin,
  URO_BitCoin,
  USDe$Cryptsy_BitCoin,
  UltraCoin_BitCoin,
  ViaCoin_BitCoin,
  VootCoin_BitCoin,
  VeriCoin_BitCoin,
  VertCoin_BitCoin,
  WhiteCoin_BitCoin,
  WorldCoin_BitCoin,
  X11Coin_BitCoin,
  JouleCoin_BitCoin,
  LibertyCoin_BitCoin,
  PrimeCoin_BitCoin,
  XXXCoin_BitCoin,
  YaCoin_BitCoin,
  YBCoin_BitCoin,
  ZcCoin_BitCoin,
  ZedCoin_BitCoin,
  ZetaCoin_BitCoin,
  AndroidsTokensV2_LiteCoin,
  AnonCoin_LiteCoin,
  AsicCoin_LiteCoin,
  AuroraCoin_LiteCoin,
  BatCoin_LiteCoin,
  BlackCoin_LiteCoin,
  CryptogenicBullion_LiteCoin,
  CloakCoin_LiteCoin,
  CHNCoin_LiteCoin,
  ColossusCoin_LiteCoin,
  CopperBars_LiteCoin,
  CryptCoin_LiteCoin,
  Continuumcoin_LiteCoin,
  Doubloons_LiteCoin,
  DigitalCoin_LiteCoin,
  DimeCoin_LiteCoin,
  DamaCoin_LiteCoin,
  Dogecoin_LiteCoin,
  DarkCoin_LiteCoin,
  DevCoin_LiteCoin,
  EarthCoin_LiteCoin,
  ElephantCoin_LiteCoin,
  EZCoin_LiteCoin,
  FlappyCoin_LiteCoin,
  FlorinCoin_LiteCoin,
  Franko_LiteCoin,
  FastCoin_LiteCoin,
  FeatherCoin_LiteCoin,
  GoldCoin_LiteCoin,
  GlyphCoin_LiteCoin,
  GameCoin_LiteCoin,
  GuerillaCoin_LiteCoin,
  InfiniteCoin_LiteCoin,
  KarmaCoin_LiteCoin,
  LeafCoin_LiteCoin,
  LottoCoin_LiteCoin,
  LiteCoinX_LiteCoin,
  MaxCoin_LiteCoin,
  MegaCoin_LiteCoin,
  MemeCoin_LiteCoin,
  KittehCoin_LiteCoin,
  MoonCoin_LiteCoin,
  MasterCoinHydro_LiteCoin,
  Netcoin_LiteCoin,
  Nxt_LiteCoin,
  NyanCoin_LiteCoin,
  Peercoin_LiteCoin,
  PhoenixCoin_LiteCoin,
  Quark_LiteCoin,
  RabbitCoin_LiteCoin,
  ReddCoin$Cryptsy_LiteCoin,
  RedCoin_LiteCoin,
  Razor_LiteCoin,
  StableCoin_LiteCoin,
  SuperCoin_LiteCoin,
  SexCoin_LiteCoin,
  TeslaCoin_LiteCoin,
  FedoraCoin_LiteCoin,
  Tickets_LiteCoin,
  VeriCoin_LiteCoin,
  VertCoin_LiteCoin,
  WorldCoin_LiteCoin,
  X11Coin_LiteCoin,
  XenCoin_LiteCoin,
  PrimeCoin_LiteCoin,
  YaCoin_LiteCoin,
  ZeitCoin_LiteCoin,
  ZetaCoin_LiteCoin
];

Map <Pair, String> CryptsyUrls = <Pair, String> {
  BitCoin_USDollar: '/markets/view/2',
  Dogecoin_USDollar: '/markets/view/182',
  DarkCoin_USDollar: '/markets/view/213',
  FeatherCoin_USDollar: '/markets/view/6',
  LiteCoin_USDollar: '/markets/view/1',
  ReddCoin$Cryptsy_USDollar: '/markets/view/262',
  FourtyTwoCoin_BitCoin: '/markets/view/141',
  AsiaCoin_BitCoin: '/markets/view/199',
  Aegis_BitCoin: '/markets/view/253',
  AlphaCoin_BitCoin: '/markets/view/57',
  AlienCoin_BitCoin: '/markets/view/273',
  AmericanCoin_BitCoin: '/markets/view/43',
  AnonCoin_BitCoin: '/markets/view/66',
  ApexCoin_BitCoin: '/markets/view/257',
  Argentum_BitCoin: '/markets/view/48',
  AuroraCoin_BitCoin: '/markets/view/160',
  BlackCoin_BitCoin: '/markets/view/179',
  BattleCoin_BitCoin: '/markets/view/142',
  Benjamins_BitCoin: '/markets/view/157',
  Betacoin_BitCoin: '/markets/view/129',
  BlueCoin_BitCoin: '/markets/view/251',
  BBQCoin_BitCoin: '/markets/view/10',
  BitBar_BitCoin: '/markets/view/23',
  BitcoinDark_BitCoin: '/markets/view/256',
  ByteCoin$Cryptsy_BitCoin: '/markets/view/49',
  BitGem_BitCoin: '/markets/view/50',
  CryptoBuck_BitCoin: '/markets/view/102',
  CACHeCoin_BitCoin: '/markets/view/154',
  CAIx_BitCoin: '/markets/view/221',
  BottleCaps_BitCoin: '/markets/view/53',
  CashCoin_BitCoin: '/markets/view/150',
  CatCoin_BitCoin: '/markets/view/136',
  CryptogenicBullion_BitCoin: '/markets/view/70',
  CinniCoin_BitCoin: '/markets/view/197',
  CloakCoin_BitCoin: '/markets/view/227',
  CopperLark_BitCoin: '/markets/view/95',
  Cosmoscoin_BitCoin: '/markets/view/74',
  CHNCoin_BitCoin: '/markets/view/8',
  ConcealCoin_BitCoin: '/markets/view/260',
  CommunityCoin_BitCoin: '/markets/view/198',
  CoolCoin_BitCoin: '/markets/view/266',
  CraftCoin_BitCoin: '/markets/view/58',
  CryptCoin_BitCoin: '/markets/view/219',
  CasinoCoin_BitCoin: '/markets/view/68',
  eMark_BitCoin: '/markets/view/131',
  Digibyte_BitCoin: '/markets/view/167',
  DigitalCoin_BitCoin: '/markets/view/26',
  Diamond_BitCoin: '/markets/view/72',
  Dogecoin_BitCoin: '/markets/view/132',
  DarkCoin_BitCoin: '/markets/view/155',
  DarkCash_BitCoin: '/markets/view/274',
  DevCoin_BitCoin: '/markets/view/40',
  EarthCoin_BitCoin: '/markets/view/139',
  ElaCoin_BitCoin: '/markets/view/12',
  Einsteinium_BitCoin: '/markets/view/188',
  Emerald_BitCoin: '/markets/view/69',
  ExeCoin_BitCoin: '/markets/view/183',
  EZCoin_BitCoin: '/markets/view/47',
  FireflyCoin_BitCoin: '/markets/view/138',
  FlutterCoin_BitCoin: '/markets/view/192',
  FractalCoin_BitCoin: '/markets/view/259',
  FreiCoin_BitCoin: '/markets/view/39',
  Franko_BitCoin: '/markets/view/33',
  FastCoin_BitCoin: '/markets/view/44',
  FeatherCoin_BitCoin: '/markets/view/5',
  GrandCoin_BitCoin: '/markets/view/82',
  Globalcoin_BitCoin: '/markets/view/76',
  GoldCoin_BitCoin: '/markets/view/30',
  Galaxycoin_BitCoin: '/markets/view/78',
  GlyphCoin_BitCoin: '/markets/view/229',
  GuerillaCoin_BitCoin: '/markets/view/241',
  HoboNickels_BitCoin: '/markets/view/80',
  HunterCoin_BitCoin: '/markets/view/249',
  HeavyCoin_BitCoin: '/markets/view/185',
  IcebergCoin_BitCoin: '/markets/view/267',
  InfiniteCoin_BitCoin: '/markets/view/59',
  IOCoin_BitCoin: '/markets/view/272',
  IXCoin_BitCoin: '/markets/view/38',
  JunkCoin_BitCoin: '/markets/view/25',
  JudgeCoin_BitCoin: '/markets/view/269',
  KlondikeCoin_BitCoin: '/markets/view/178',
  KeyCoin_BitCoin: '/markets/view/255',
  KrugerCoin_BitCoin: '/markets/view/65',
  LegendaryCoin_BitCoin: '/markets/view/204',
  Lucky7Coin_BitCoin: '/markets/view/116',
  LuckyCoin_BitCoin: '/markets/view/34',
  LiteBar_BitCoin: '/markets/view/202',
  LiteCoin_BitCoin: '/markets/view/3',
  LiteCoinX_BitCoin: '/markets/view/233',
  LycanCoin_BitCoin: '/markets/view/177',
  MaxCoin_BitCoin: '/markets/view/152',
  MegaCoin_BitCoin: '/markets/view/45',
  Minerals_BitCoin: '/markets/view/258',
  MintCoin_BitCoin: '/markets/view/156',
  MiningContract1_BitCoin: '/markets/view/187',
  MiningContract2_BitCoin: '/markets/view/196',
  MinCoin_BitCoin: '/markets/view/7',
  MurrayCoin_BitCoin: '/markets/view/189',
  MyriadCoin_BitCoin: '/markets/view/200',
  MazaCoin_BitCoin: '/markets/view/164',
  NanoToken_BitCoin: '/markets/view/64',
  NautilusCoin_BitCoin: '/markets/view/207',
  NavajoCoin_BitCoin: '/markets/view/252',
  Nibble_BitCoin: '/markets/view/32',
  NeoCoin_BitCoin: '/markets/view/90',
  Netcoin_BitCoin: '/markets/view/134',
  NameCoin_BitCoin: '/markets/view/29',
  NobleCoin_BitCoin: '/markets/view/264',
  NoirBits_BitCoin: '/markets/view/54',
  NoirShares_BitCoin: '/markets/view/211',
  NovaCoin_BitCoin: '/markets/view/13',
  Nxt_BitCoin: '/markets/view/159',
  NyanCoin_BitCoin: '/markets/view/184',
  Orbitcoin_BitCoin: '/markets/view/75',
  OpenSourceCoin_BitCoin: '/markets/view/144',
  PhilosopherStone_BitCoin: '/markets/view/86',
  CryptsyPoints_BitCoin: '/markets/view/120',
  PotCoin_BitCoin: '/markets/view/173',
  Peercoin_BitCoin: '/markets/view/28',
  PseudoCoin_BitCoin: '/markets/view/268',
  BitsharesPTS_BitCoin: '/markets/view/119',
  PhoenixCoin_BitCoin: '/markets/view/31',
  PayCoin_BitCoin: '/markets/view/92',
  Quark_BitCoin: '/markets/view/71',
  ReddCoin$Cryptsy_BitCoin: '/markets/view/169',
  RonPaulCoin_BitCoin: '/markets/view/143',
  RotoCoin_BitCoin: '/markets/view/235',
  RoyalCoin_BitCoin: '/markets/view/9',
  Razor_BitCoin: '/markets/view/237',
  SaturnCoinV2_BitCoin: '/markets/view/232',
  StableCoin_BitCoin: '/markets/view/51',
  SilkCoin$Cryptsy_BitCoin: '/markets/view/225',
  SaffronCoin_BitCoin: '/markets/view/270',
  ShieldCoin_BitCoin: '/markets/view/248',
  SmartCoin_BitCoin: '/markets/view/158',
  SpainCoin_BitCoin: '/markets/view/180',
  Spots_BitCoin: '/markets/view/81',
  SecureCoin_BitCoin: '/markets/view/88',
  StarCoin_BitCoin: '/markets/view/83',
  SuperCoin_BitCoin: '/markets/view/239',
  SexCoin_BitCoin: '/markets/view/153',
  Sync_BitCoin: '/markets/view/271',
  TagCoin_BitCoin: '/markets/view/117',
  TakCoin_BitCoin: '/markets/view/166',
  TekCoin_BitCoin: '/markets/view/114',
  TeslaCoin_BitCoin: '/markets/view/223',
  TigerCoin_BitCoin: '/markets/view/130',
  TorCoin_BitCoin: '/markets/view/250',
  TerraCoin_BitCoin: '/markets/view/27',
  UnbreakableCoin_BitCoin: '/markets/view/203',
  Unobtanium_BitCoin: '/markets/view/133',
  URO_BitCoin: '/markets/view/247',
  USDe$Cryptsy_BitCoin: '/markets/view/201',
  UltraCoin_BitCoin: '/markets/view/163',
  ViaCoin_BitCoin: '/markets/view/261',
  VootCoin_BitCoin: '/markets/view/254',
  VeriCoin_BitCoin: '/markets/view/209',
  VertCoin_BitCoin: '/markets/view/151',
  WhiteCoin_BitCoin: '/markets/view/195',
  WorldCoin_BitCoin: '/markets/view/14',
  X11Coin_BitCoin: '/markets/view/210',
  JouleCoin_BitCoin: '/markets/view/115',
  LibertyCoin_BitCoin: '/markets/view/208',
  PrimeCoin_BitCoin: '/markets/view/63',
  XXXCoin_BitCoin: '/markets/view/265',
  YaCoin_BitCoin: '/markets/view/11',
  YBCoin_BitCoin: '/markets/view/73',
  ZcCoin_BitCoin: '/markets/view/140',
  ZedCoin_BitCoin: '/markets/view/170',
  ZetaCoin_BitCoin: '/markets/view/85',
  AndroidsTokensV2_LiteCoin: '/markets/view/94',
  AnonCoin_LiteCoin: '/markets/view/121',
  AsicCoin_LiteCoin: '/markets/view/111',
  AuroraCoin_LiteCoin: '/markets/view/161',
  BatCoin_LiteCoin: '/markets/view/186',
  BlackCoin_LiteCoin: '/markets/view/191',
  CryptogenicBullion_LiteCoin: '/markets/view/123',
  CloakCoin_LiteCoin: '/markets/view/228',
  CHNCoin_LiteCoin: '/markets/view/17',
  ColossusCoin_LiteCoin: '/markets/view/109',
  CopperBars_LiteCoin: '/markets/view/91',
  CryptCoin_LiteCoin: '/markets/view/220',
  Continuumcoin_LiteCoin: '/markets/view/175',
  Doubloons_LiteCoin: '/markets/view/46',
  DigitalCoin_LiteCoin: '/markets/view/96',
  DimeCoin_LiteCoin: '/markets/view/206',
  DamaCoin_LiteCoin: '/markets/view/194',
  Dogecoin_LiteCoin: '/markets/view/135',
  DarkCoin_LiteCoin: '/markets/view/214',
  DevCoin_LiteCoin: '/markets/view/52',
  EarthCoin_LiteCoin: '/markets/view/244',
  ElephantCoin_LiteCoin: '/markets/view/93',
  EZCoin_LiteCoin: '/markets/view/55',
  FlappyCoin_LiteCoin: '/markets/view/246',
  FlorinCoin_LiteCoin: '/markets/view/61',
  Franko_LiteCoin: '/markets/view/171',
  FastCoin_LiteCoin: '/markets/view/124',
  FeatherCoin_LiteCoin: '/markets/view/4',
  GoldCoin_LiteCoin: '/markets/view/36',
  GlyphCoin_LiteCoin: '/markets/view/230',
  GameCoin_LiteCoin: '/markets/view/84',
  GuerillaCoin_LiteCoin: '/markets/view/242',
  InfiniteCoin_LiteCoin: '/markets/view/60',
  KarmaCoin_LiteCoin: '/markets/view/193',
  LeafCoin_LiteCoin: '/markets/view/245',
  LottoCoin_LiteCoin: '/markets/view/243',
  LiteCoinX_LiteCoin: '/markets/view/234',
  MaxCoin_LiteCoin: '/markets/view/218',
  MegaCoin_LiteCoin: '/markets/view/100',
  MemeCoin_LiteCoin: '/markets/view/56',
  KittehCoin_LiteCoin: '/markets/view/231',
  MoonCoin_LiteCoin: '/markets/view/145',
  MasterCoinHydro_LiteCoin: '/markets/view/62',
  Netcoin_LiteCoin: '/markets/view/108',
  Nxt_LiteCoin: '/markets/view/162',
  NyanCoin_LiteCoin: '/markets/view/263',
  Peercoin_LiteCoin: '/markets/view/125',
  PhoenixCoin_LiteCoin: '/markets/view/101',
  Quark_LiteCoin: '/markets/view/126',
  RabbitCoin_LiteCoin: '/markets/view/190',
  ReddCoin$Cryptsy_LiteCoin: '/markets/view/212',
  RedCoin_LiteCoin: '/markets/view/87',
  Razor_LiteCoin: '/markets/view/238',
  StableCoin_LiteCoin: '/markets/view/128',
  SuperCoin_LiteCoin: '/markets/view/240',
  SexCoin_LiteCoin: '/markets/view/98',
  TeslaCoin_LiteCoin: '/markets/view/224',
  FedoraCoin_LiteCoin: '/markets/view/147',
  Tickets_LiteCoin: '/markets/view/107',
  VeriCoin_LiteCoin: '/markets/view/215',
  VertCoin_LiteCoin: '/markets/view/217',
  WorldCoin_LiteCoin: '/markets/view/21',
  X11Coin_LiteCoin: '/markets/view/216',
  XenCoin_LiteCoin: '/markets/view/67',
  PrimeCoin_LiteCoin: '/markets/view/106',
  YaCoin_LiteCoin: '/markets/view/22',
  ZeitCoin_LiteCoin: '/markets/view/176',
  ZetaCoin_LiteCoin: '/markets/view/127'
};
