part of coin;


List<Coin> CoinSwapCoins = <Coin> [
  SixtySixCoin,
  BitCoin,
  AsiaCoin,
  Aidbit,
  Ascentcoin,
  BlackCoin,
  BellaCoin,
  Buylatercoin,
  BlueCoin,
  Blazecoin,
  Bitmoney,
  Borgcoin,
  GlobalBoost,
  Banksycoin,
  CaiShen,
  BottleCaps,
  CAPTcoin,
  Chakracoin,
  Cloak,
  Compasscoin,
  Compucoin,
  Credits,
  Dogecoin,
  DarkCoin,
  EmbargoCoin,
  FractalCoin,
  Fusecoin,
  GROUPCoin,
  GunCoin,
  Hyperstake,
  ImperialcoinIMP,
  IOCoin,
  ImperialcoinIPC,
  Koolio,
  KryptKoin,
  LATIUM,
  ElectronicLIRA,
  LiteCoin,
  Latinum,
  Multicoin,
  PotCoin,
  PeoplesCurrency,
  PayProCoin,
  PureCoin,
  RobotSexNickels,
  Shadowcoin,
  Shinycoin,
  Shibe,
  STLcoin,
  ViaCoin,
  VirtualminingCoin,
  GoldReserve,
  YellowCoin,
  ActiveCoin,
  Bunnycoin,
  CornerstoneCoin,
  Dojecoin,
  Hobbitcoin,
  HTMLcoin
];

Map<Pair, String> CoinSwapIds = <Pair, String> {
  SixtySixCoin_BitCoin: '5828',
  AsiaCoin_BitCoin: '5926',
  Aidbit_BitCoin: '6049',
  Ascentcoin_BitCoin: '5973',
  BlackCoin_BitCoin: '5882',
  BellaCoin_BitCoin: '5830',
  Buylatercoin_BitCoin: '6035',
  BlueCoin_BitCoin: '5934',
  Blazecoin_BitCoin: '5991',
  Bitmoney_BitCoin: '6021',
  Borgcoin_BitCoin: '5995',
  GlobalBoost_BitCoin: '5940',
  Banksycoin_BitCoin: '6029',
  CaiShen_BitCoin: '5963',
  BottleCaps_BitCoin: '6017',
  CAPTcoin_BitCoin: '6041',
  Chakracoin_BitCoin: '5960',
  Cloak_BitCoin: '6061',
  Compasscoin_BitCoin: '5954',
  Compucoin_BitCoin: '6001',
  Credits_BitCoin: '6033',
  Dogecoin_BitCoin: '5835',
  DarkCoin_BitCoin: '5836',
  EmbargoCoin_BitCoin: '5971',
  FractalCoin_BitCoin: '6009',
  Fusecoin_BitCoin: '6053',
  GROUPCoin_BitCoin: '6067',
  GunCoin_BitCoin: '5946',
  Hyperstake_BitCoin: '6013',
  ImperialcoinIMP_BitCoin: '6019',
  IOCoin_BitCoin: '6065',
  ImperialcoinIPC_BitCoin: '6023',
  Koolio_BitCoin: '6031',
  KryptKoin_BitCoin: '5997',
  LATIUM_BitCoin: '5999',
  ElectronicLIRA_BitCoin: '5948',
  LiteCoin_BitCoin: '5846',
  Latinum_BitCoin: '6015',
  Multicoin_BitCoin: '6043',
  PotCoin_BitCoin: '5858',
  PeoplesCurrency_BitCoin: '6027',
  PayProCoin_BitCoin: '6025',
  PureCoin_BitCoin: '6003',
  RobotSexNickels_BitCoin: '6037',
  Shadowcoin_BitCoin: '6057',
  Shinycoin_BitCoin: '6011',
  Shibe_BitCoin: '6059',
  STLcoin_BitCoin: '5956',
  ViaCoin_BitCoin: '6063',
  VirtualminingCoin_BitCoin: '5952',
  GoldReserve_BitCoin: '6051',
  YellowCoin_BitCoin: '5930',
  ActiveCoin_Dogecoin: '6006',
  Borgcoin_Dogecoin: '5996',
  Bunnycoin_Dogecoin: '5970',
  CornerstoneCoin_Dogecoin: '5980',
  Dojecoin_Dogecoin: '5978',
  Hobbitcoin_Dogecoin: '5968',
  HTMLcoin_Dogecoin: '5959'
};

List<Pair> CoinSwapPairs = <Pair> [
  SixtySixCoin_BitCoin,
  AsiaCoin_BitCoin,
  Aidbit_BitCoin,
  Ascentcoin_BitCoin,
  BlackCoin_BitCoin,
  BellaCoin_BitCoin,
  Buylatercoin_BitCoin,
  BlueCoin_BitCoin,
  Blazecoin_BitCoin,
  Bitmoney_BitCoin,
  Borgcoin_BitCoin,
  GlobalBoost_BitCoin,
  Banksycoin_BitCoin,
  CaiShen_BitCoin,
  BottleCaps_BitCoin,
  CAPTcoin_BitCoin,
  Chakracoin_BitCoin,
  Cloak_BitCoin,
  Compasscoin_BitCoin,
  Compucoin_BitCoin,
  Credits_BitCoin,
  Dogecoin_BitCoin,
  DarkCoin_BitCoin,
  EmbargoCoin_BitCoin,
  FractalCoin_BitCoin,
  Fusecoin_BitCoin,
  GROUPCoin_BitCoin,
  GunCoin_BitCoin,
  Hyperstake_BitCoin,
  ImperialcoinIMP_BitCoin,
  IOCoin_BitCoin,
  ImperialcoinIPC_BitCoin,
  Koolio_BitCoin,
  KryptKoin_BitCoin,
  LATIUM_BitCoin,
  ElectronicLIRA_BitCoin,
  LiteCoin_BitCoin,
  Latinum_BitCoin,
  Multicoin_BitCoin,
  PotCoin_BitCoin,
  PeoplesCurrency_BitCoin,
  PayProCoin_BitCoin,
  PureCoin_BitCoin,
  RobotSexNickels_BitCoin,
  Shadowcoin_BitCoin,
  Shinycoin_BitCoin,
  Shibe_BitCoin,
  STLcoin_BitCoin,
  ViaCoin_BitCoin,
  VirtualminingCoin_BitCoin,
  GoldReserve_BitCoin,
  YellowCoin_BitCoin,
  ActiveCoin_Dogecoin,
  Borgcoin_Dogecoin,
  Bunnycoin_Dogecoin,
  CornerstoneCoin_Dogecoin,
  Dojecoin_Dogecoin,
  Hobbitcoin_Dogecoin,
  HTMLcoin_Dogecoin
];

Map <Pair, String> CoinSwapUrls = <Pair, String> {
  SixtySixCoin_BitCoin: '/market/66/BTC',
  AsiaCoin_BitCoin: '/market/AC/BTC',
  Aidbit_BitCoin: '/market/AID/BTC',
  Ascentcoin_BitCoin: '/market/ASCE/BTC',
  BlackCoin_BitCoin: '/market/BC/BTC',
  BellaCoin_BitCoin: '/market/BELA/BTC',
  Buylatercoin_BitCoin: '/market/BLTR/BTC',
  BlueCoin_BitCoin: '/market/BLU/BTC',
  Blazecoin_BitCoin: '/market/BLZ/BTC',
  Bitmoney_BitCoin: '/market/BMY/BTC',
  Borgcoin_BitCoin: '/market/BORG/BTC',
  GlobalBoost_BitCoin: '/market/BST/BTC',
  Banksycoin_BitCoin: '/market/BSY/BTC',
  CaiShen_BitCoin: '/market/CAIx/BTC',
  BottleCaps_BitCoin: '/market/CAP/BTC',
  CAPTcoin_BitCoin: '/market/CAPT/BTC',
  Chakracoin_BitCoin: '/market/CKC/BTC',
  Cloak_BitCoin: '/market/CLOAK/BTC',
  Compasscoin_BitCoin: '/market/CPC/BTC',
  Compucoin_BitCoin: '/market/CPN/BTC',
  Credits_BitCoin: '/market/CRD/BTC',
  Dogecoin_BitCoin: '/market/DOGE/BTC',
  DarkCoin_BitCoin: '/market/DRK/BTC',
  EmbargoCoin_BitCoin: '/market/EBG/BTC',
  FractalCoin_BitCoin: '/market/FRAC/BTC',
  Fusecoin_BitCoin: '/market/FUSE/BTC',
  GROUPCoin_BitCoin: '/market/GPC/BTC',
  GunCoin_BitCoin: '/market/GUN/BTC',
  Hyperstake_BitCoin: '/market/HYP/BTC',
  ImperialcoinIMP_BitCoin: '/market/IMP/BTC',
  IOCoin_BitCoin: '/market/IOC/BTC',
  ImperialcoinIPC_BitCoin: '/market/IPC/BTC',
  Koolio_BitCoin: '/market/KOOL/BTC',
  KryptKoin_BitCoin: '/market/KTK/BTC',
  LATIUM_BitCoin: '/market/LAT/BTC',
  ElectronicLIRA_BitCoin: '/market/LIRE/BTC',
  LiteCoin_BitCoin: '/market/LTC/BTC',
  Latinum_BitCoin: '/market/LTM/BTC',
  Multicoin_BitCoin: '/market/MC/BTC',
  PotCoin_BitCoin: '/market/POT/BTC',
  PeoplesCurrency_BitCoin: '/market/PPL/BTC',
  PayProCoin_BitCoin: '/market/PRO/BTC',
  PureCoin_BitCoin: '/market/PURE/BTC',
  RobotSexNickels_BitCoin: '/market/RSN/BTC',
  Shadowcoin_BitCoin: '/market/SDC/BTC',
  Shinycoin_BitCoin: '/market/SHC/BTC',
  Shibe_BitCoin: '/market/SHIBE/BTC',
  STLcoin_BitCoin: '/market/STL/BTC',
  ViaCoin_BitCoin: '/market/VIA/BTC',
  VirtualminingCoin_BitCoin: '/market/VMC/BTC',
  GoldReserve_BitCoin: '/market/XGR/BTC',
  YellowCoin_BitCoin: '/market/YC/BTC',
  ActiveCoin_Dogecoin: '/market/ACT/DOGE',
  Borgcoin_Dogecoin: '/market/BORG/DOGE',
  Bunnycoin_Dogecoin: '/market/BUNNY/DOGE',
  CornerstoneCoin_Dogecoin: '/market/CCX/DOGE',
  Dojecoin_Dogecoin: '/market/DOJE/DOGE',
  Hobbitcoin_Dogecoin: '/market/HBC/DOGE',
  HTMLcoin_Dogecoin: '/market/HTML/DOGE'
};
