part of coin;


List<Coin> PoloniexCoins = <Coin> [
  OneCRedit,
  BitCoin,
  AppleByte,
  Aiden,
  AEONCoin,
  Aerocoin,
  AuroraCoin,
  Axis,
  BitBlock,
  Boolberry,
  BlackCoin,
  BTCtalkcoin,
  Bytecoin$Poloniex,
  BlackDragonCoin,
  BellaCoin,
  Bitstar,
  BlueCoin,
  BonusCoin,
  Bones,
  BoostCoin,
  BitcoinDark,
  Bitmark,
  BurnerCoin,
  CACHeCoin,
  CryptographicAnomaly,
  Chancecoin,
  CinniCoin,
  CLAMS,
  ConcealCoin,
  CNote,
  CommunityCoin,
  CryptCoin,
  Curecoin,
  ConspiracyCoin,
  CarpeDiemCoin,
  DistroCoin,
  Dogecoin,
  DarkCoin,
  DarkCash,
  DvoraKoin,
  EBTcoin,
  ElectronicGulden,
  Einsteinium,
  Entropycoin,
  ExeCoin,
  Fantomcoin,
  FlutterCoin,
  FractalCoin,
  FVZCoin,
  Fuzon,
  GlobalDenomination,
  Giarcoin,
  GameleagueCoin,
  GoldEagles,
  GROUPCoin,
  Gridcoin,
  GroestlCoin,
  GuerillaCoin,
  Hirocoin,
  Hotcoin,
  HunterCoin,
  IXCoin,
  jl777hodl,
  JackpotCoin,
  KeyCoin,
  Logicoin,
  LeagueCoin,
  LiteCoin,
  LiteCoinX,
  MaidSafeCoin,
  MastiffCoin,
  MonetaVerde,
  CryptoMETH,
  MillionaireCoin,
  Minerals,
  MintCoin,
  MemoryCoin,
  MiningShares1GH,
  Monocle,
  microCoin,
  Marscoin,
  Mastercoin,
  MyriadCoin,
  N5coin,
  NAS,
  NautilusCoin,
  Navajo,
  Coin20,
  NextHorizon,
  Nanolite,
  NameCoin,
  NobleCoin,
  DNotes,
  NoirShares,
  NTX,
  Nxt,
  Pawncoin,
  Pinkcoin,
  NewPiggycoin,
  ParallaxCoin,
  Premine,
  PotCoin,
  Peercoin,
  ProsperCoin,
  Particle,
  Protoshares,
  QubitCoin,
  Qibuck,
  QuazarCoin,
  Qora,
  Rubycoin,
  Reddcoin$Poloniex,
  Riecoin,
  Razor,
  ShibeCoin,
  ShopX,
  Silkcoin$Poloniex,
  SocialCoin,
  SourceCoin,
  Stellar,
  Sync,
  Talkcoin,
  TorCoin,
  TrustPlus,
  URO,
  USDE$Poloniex,
  ViaCoin,
  VootCoin,
  VeriCoin,
  VertCoin,
  WhiteCoin,
  WorldCoin,
  InsanityCoin,
  APICoin,
  BitcoinPlus,
  XCurrency,
  Counterparty,
  duckNote,
  Honorcoin,
  LibertyCoin,
  Monero,
  PrimeCoin,
  StabilityShares,
  YACCoin,
  Yangcoin,
  Yincoin,
  InfiniteCoin
];

Map<Pair, String> PoloniexIds = <Pair, String> {
  OneCRedit_BitCoin: 'btc_1cr',
  AppleByte_BitCoin: 'btc_aby',
  Aiden_BitCoin: 'btc_adn',
  AEONCoin_BitCoin: 'btc_aeon',
  Aerocoin_BitCoin: 'btc_aero',
  AuroraCoin_BitCoin: 'btc_aur',
  Axis_BitCoin: 'btc_axis',
  BitBlock_BitCoin: 'btc_bbl',
  Boolberry_BitCoin: 'btc_bbr',
  BlackCoin_BitCoin: 'btc_bc',
  BTCtalkcoin_BitCoin: 'btc_bcc',
  Bytecoin$Poloniex_BitCoin: 'btc_bcn',
  BlackDragonCoin_BitCoin: 'btc_bdc',
  BellaCoin_BitCoin: 'btc_bela',
  Bitstar_BitCoin: 'btc_bits',
  BlueCoin_BitCoin: 'btc_blu',
  BonusCoin_BitCoin: 'btc_bns',
  Bones_BitCoin: 'btc_bones',
  BoostCoin_BitCoin: 'btc_bost',
  BitcoinDark_BitCoin: 'btc_btcd',
  Bitmark_BitCoin: 'btc_btm',
  BurnerCoin_BitCoin: 'btc_burn',
  CACHeCoin_BitCoin: 'btc_cach',
  CryptographicAnomaly_BitCoin: 'btc_cga',
  Chancecoin_BitCoin: 'btc_cha',
  CinniCoin_BitCoin: 'btc_cinni',
  CLAMS_BitCoin: 'btc_clam',
  ConcealCoin_BitCoin: 'btc_cnl',
  CNote_BitCoin: 'btc_cnote',
  CommunityCoin_BitCoin: 'btc_comm',
  CryptCoin_BitCoin: 'btc_crypt',
  Curecoin_BitCoin: 'btc_cure',
  ConspiracyCoin_BitCoin: 'btc_cyc',
  CarpeDiemCoin_BitCoin: 'btc_diem',
  DistroCoin_BitCoin: 'btc_dis',
  Dogecoin_BitCoin: 'btc_doge',
  DarkCoin_BitCoin: 'btc_drk',
  DarkCash_BitCoin: 'btc_drkc',
  DvoraKoin_BitCoin: 'btc_dvk',
  EBTcoin_BitCoin: 'btc_ebt',
  ElectronicGulden_BitCoin: 'btc_efl',
  Einsteinium_BitCoin: 'btc_emc2',
  Entropycoin_BitCoin: 'btc_enc',
  ExeCoin_BitCoin: 'btc_exe',
  Fantomcoin_BitCoin: 'btc_fcn',
  FlutterCoin_BitCoin: 'btc_flt',
  FractalCoin_BitCoin: 'btc_frac',
  FVZCoin_BitCoin: 'btc_fvz',
  Fuzon_BitCoin: 'btc_fzn',
  GlobalDenomination_BitCoin: 'btc_gdn',
  Giarcoin_BitCoin: 'btc_giar',
  GameleagueCoin_BitCoin: 'btc_gml',
  GoldEagles_BitCoin: 'btc_gold',
  GROUPCoin_BitCoin: 'btc_gpc',
  Gridcoin_BitCoin: 'btc_grc',
  GroestlCoin_BitCoin: 'btc_grs',
  GuerillaCoin_BitCoin: 'btc_gue',
  Hirocoin_BitCoin: 'btc_hiro',
  Hotcoin_BitCoin: 'btc_hot',
  HunterCoin_BitCoin: 'btc_huc',
  IXCoin_BitCoin: 'btc_ixc',
  jl777hodl_BitCoin: 'btc_jlh',
  JackpotCoin_BitCoin: 'btc_jpc',
  KeyCoin_BitCoin: 'btc_key',
  Logicoin_BitCoin: 'btc_lgc',
  LeagueCoin_BitCoin: 'btc_lol',
  LiteCoin_BitCoin: 'btc_ltc',
  LiteCoinX_BitCoin: 'btc_ltcx',
  MaidSafeCoin_BitCoin: 'btc_maid',
  MastiffCoin_BitCoin: 'btc_mast',
  MonetaVerde_BitCoin: 'btc_mcn',
  CryptoMETH_BitCoin: 'btc_meth',
  MillionaireCoin_BitCoin: 'btc_mil',
  Minerals_BitCoin: 'btc_min',
  MintCoin_BitCoin: 'btc_mint',
  MemoryCoin_BitCoin: 'btc_mmc',
  MiningShares1GH_BitCoin: 'btc_mns1',
  Monocle_BitCoin: 'btc_mon',
  microCoin_BitCoin: 'btc_mrc',
  Marscoin_BitCoin: 'btc_mrs',
  Mastercoin_BitCoin: 'btc_msc',
  MyriadCoin_BitCoin: 'btc_myr',
  N5coin_BitCoin: 'btc_n5x',
  NAS_BitCoin: 'btc_nas',
  NautilusCoin_BitCoin: 'btc_naut',
  Navajo_BitCoin: 'btc_nav',
  Coin20_BitCoin: 'btc_nc2',
  NextHorizon_BitCoin: 'btc_nhz',
  Nanolite_BitCoin: 'btc_nl',
  NameCoin_BitCoin: 'btc_nmc',
  NobleCoin_BitCoin: 'btc_nobl',
  DNotes_BitCoin: 'btc_note',
  NoirShares_BitCoin: 'btc_nrs',
  NTX_BitCoin: 'btc_ntx',
  Nxt_BitCoin: 'btc_nxt',
  Pawncoin_BitCoin: 'btc_pawn',
  Pinkcoin_BitCoin: 'btc_pc',
  NewPiggycoin_BitCoin: 'btc_piggy',
  ParallaxCoin_BitCoin: 'btc_plx',
  Premine_BitCoin: 'btc_pmc',
  PotCoin_BitCoin: 'btc_pot',
  Peercoin_BitCoin: 'btc_ppc',
  ProsperCoin_BitCoin: 'btc_prc',
  Particle_BitCoin: 'btc_prt',
  Protoshares_BitCoin: 'btc_pts',
  QubitCoin_BitCoin: 'btc_q2c',
  Qibuck_BitCoin: 'btc_qbk',
  QuazarCoin_BitCoin: 'btc_qcn',
  Qora_BitCoin: 'btc_qora',
  Rubycoin_BitCoin: 'btc_rby',
  Reddcoin$Poloniex_BitCoin: 'btc_redd',
  Riecoin_BitCoin: 'btc_ric',
  Razor_BitCoin: 'btc_rzr',
  ShibeCoin_BitCoin: 'btc_shibe',
  ShopX_BitCoin: 'btc_shopx',
  Silkcoin$Poloniex_BitCoin: 'btc_silk',
  SocialCoin_BitCoin: 'btc_soc',
  SourceCoin_BitCoin: 'btc_srcc',
  Stellar_BitCoin: 'btc_str',
  Sync_BitCoin: 'btc_sync',
  Talkcoin_BitCoin: 'btc_tac',
  TorCoin_BitCoin: 'btc_tor',
  TrustPlus_BitCoin: 'btc_trust',
  URO_BitCoin: 'btc_uro',
  USDE$Poloniex_BitCoin: 'btc_usde',
  ViaCoin_BitCoin: 'btc_via',
  VootCoin_BitCoin: 'btc_voot',
  VeriCoin_BitCoin: 'btc_vrc',
  VertCoin_BitCoin: 'btc_vtc',
  WhiteCoin_BitCoin: 'btc_wc',
  WorldCoin_BitCoin: 'btc_wdc',
  InsanityCoin_BitCoin: 'btc_wolf',
  APICoin_BitCoin: 'btc_xap',
  BitcoinPlus_BitCoin: 'btc_xbc',
  XCurrency_BitCoin: 'btc_xc',
  Counterparty_BitCoin: 'btc_xcp',
  duckNote_BitCoin: 'btc_xdn',
  Honorcoin_BitCoin: 'btc_xhc',
  LibertyCoin_BitCoin: 'btc_xlb',
  Monero_BitCoin: 'btc_xmr',
  PrimeCoin_BitCoin: 'btc_xpm',
  StabilityShares_BitCoin: 'btc_xsi',
  YACCoin_BitCoin: 'btc_yacc',
  Yangcoin_BitCoin: 'btc_yang',
  Yincoin_BitCoin: 'btc_yin',
  BlackCoin_Monero: 'xmr_bc',
  Bytecoin$Poloniex_Monero: 'xmr_bcn',
  BitcoinDark_Monero: 'xmr_btcd',
  CarpeDiemCoin_Monero: 'xmr_diem',
  DarkCoin_Monero: 'xmr_drk',
  InfiniteCoin_Monero: 'xmr_ifc',
  LiteCoin_Monero: 'xmr_ltc',
  MaidSafeCoin_Monero: 'xmr_maid',
  Nxt_Monero: 'xmr_nxt',
  Qora_Monero: 'xmr_qora',
  duckNote_Monero: 'xmr_xdn'
};

List<Pair> PoloniexPairs = <Pair> [
  OneCRedit_BitCoin,
  AppleByte_BitCoin,
  Aiden_BitCoin,
  AEONCoin_BitCoin,
  Aerocoin_BitCoin,
  AuroraCoin_BitCoin,
  Axis_BitCoin,
  BitBlock_BitCoin,
  Boolberry_BitCoin,
  BlackCoin_BitCoin,
  BTCtalkcoin_BitCoin,
  Bytecoin$Poloniex_BitCoin,
  BlackDragonCoin_BitCoin,
  BellaCoin_BitCoin,
  Bitstar_BitCoin,
  BlueCoin_BitCoin,
  BonusCoin_BitCoin,
  Bones_BitCoin,
  BoostCoin_BitCoin,
  BitcoinDark_BitCoin,
  Bitmark_BitCoin,
  BurnerCoin_BitCoin,
  CACHeCoin_BitCoin,
  CryptographicAnomaly_BitCoin,
  Chancecoin_BitCoin,
  CinniCoin_BitCoin,
  CLAMS_BitCoin,
  ConcealCoin_BitCoin,
  CNote_BitCoin,
  CommunityCoin_BitCoin,
  CryptCoin_BitCoin,
  Curecoin_BitCoin,
  ConspiracyCoin_BitCoin,
  CarpeDiemCoin_BitCoin,
  DistroCoin_BitCoin,
  Dogecoin_BitCoin,
  DarkCoin_BitCoin,
  DarkCash_BitCoin,
  DvoraKoin_BitCoin,
  EBTcoin_BitCoin,
  ElectronicGulden_BitCoin,
  Einsteinium_BitCoin,
  Entropycoin_BitCoin,
  ExeCoin_BitCoin,
  Fantomcoin_BitCoin,
  FlutterCoin_BitCoin,
  FractalCoin_BitCoin,
  FVZCoin_BitCoin,
  Fuzon_BitCoin,
  GlobalDenomination_BitCoin,
  Giarcoin_BitCoin,
  GameleagueCoin_BitCoin,
  GoldEagles_BitCoin,
  GROUPCoin_BitCoin,
  Gridcoin_BitCoin,
  GroestlCoin_BitCoin,
  GuerillaCoin_BitCoin,
  Hirocoin_BitCoin,
  Hotcoin_BitCoin,
  HunterCoin_BitCoin,
  IXCoin_BitCoin,
  jl777hodl_BitCoin,
  JackpotCoin_BitCoin,
  KeyCoin_BitCoin,
  Logicoin_BitCoin,
  LeagueCoin_BitCoin,
  LiteCoin_BitCoin,
  LiteCoinX_BitCoin,
  MaidSafeCoin_BitCoin,
  MastiffCoin_BitCoin,
  MonetaVerde_BitCoin,
  CryptoMETH_BitCoin,
  MillionaireCoin_BitCoin,
  Minerals_BitCoin,
  MintCoin_BitCoin,
  MemoryCoin_BitCoin,
  MiningShares1GH_BitCoin,
  Monocle_BitCoin,
  microCoin_BitCoin,
  Marscoin_BitCoin,
  Mastercoin_BitCoin,
  MyriadCoin_BitCoin,
  N5coin_BitCoin,
  NAS_BitCoin,
  NautilusCoin_BitCoin,
  Navajo_BitCoin,
  Coin20_BitCoin,
  NextHorizon_BitCoin,
  Nanolite_BitCoin,
  NameCoin_BitCoin,
  NobleCoin_BitCoin,
  DNotes_BitCoin,
  NoirShares_BitCoin,
  NTX_BitCoin,
  Nxt_BitCoin,
  Pawncoin_BitCoin,
  Pinkcoin_BitCoin,
  NewPiggycoin_BitCoin,
  ParallaxCoin_BitCoin,
  Premine_BitCoin,
  PotCoin_BitCoin,
  Peercoin_BitCoin,
  ProsperCoin_BitCoin,
  Particle_BitCoin,
  Protoshares_BitCoin,
  QubitCoin_BitCoin,
  Qibuck_BitCoin,
  QuazarCoin_BitCoin,
  Qora_BitCoin,
  Rubycoin_BitCoin,
  Reddcoin$Poloniex_BitCoin,
  Riecoin_BitCoin,
  Razor_BitCoin,
  ShibeCoin_BitCoin,
  ShopX_BitCoin,
  Silkcoin$Poloniex_BitCoin,
  SocialCoin_BitCoin,
  SourceCoin_BitCoin,
  Stellar_BitCoin,
  Sync_BitCoin,
  Talkcoin_BitCoin,
  TorCoin_BitCoin,
  TrustPlus_BitCoin,
  URO_BitCoin,
  USDE$Poloniex_BitCoin,
  ViaCoin_BitCoin,
  VootCoin_BitCoin,
  VeriCoin_BitCoin,
  VertCoin_BitCoin,
  WhiteCoin_BitCoin,
  WorldCoin_BitCoin,
  InsanityCoin_BitCoin,
  APICoin_BitCoin,
  BitcoinPlus_BitCoin,
  XCurrency_BitCoin,
  Counterparty_BitCoin,
  duckNote_BitCoin,
  Honorcoin_BitCoin,
  LibertyCoin_BitCoin,
  Monero_BitCoin,
  PrimeCoin_BitCoin,
  StabilityShares_BitCoin,
  YACCoin_BitCoin,
  Yangcoin_BitCoin,
  Yincoin_BitCoin,
  BlackCoin_Monero,
  Bytecoin$Poloniex_Monero,
  BitcoinDark_Monero,
  CarpeDiemCoin_Monero,
  DarkCoin_Monero,
  InfiniteCoin_Monero,
  LiteCoin_Monero,
  MaidSafeCoin_Monero,
  Nxt_Monero,
  Qora_Monero,
  duckNote_Monero
];

Map <Pair, String> PoloniexUrls = <Pair, String> {
  OneCRedit_BitCoin: '/exchange/btc_1cr',
  AppleByte_BitCoin: '/exchange/btc_aby',
  Aiden_BitCoin: '/exchange/btc_adn',
  AEONCoin_BitCoin: '/exchange/btc_aeon',
  Aerocoin_BitCoin: '/exchange/btc_aero',
  AuroraCoin_BitCoin: '/exchange/btc_aur',
  Axis_BitCoin: '/exchange/btc_axis',
  BitBlock_BitCoin: '/exchange/btc_bbl',
  Boolberry_BitCoin: '/exchange/btc_bbr',
  BlackCoin_BitCoin: '/exchange/btc_bc',
  BTCtalkcoin_BitCoin: '/exchange/btc_bcc',
  Bytecoin$Poloniex_BitCoin: '/exchange/btc_bcn',
  BlackDragonCoin_BitCoin: '/exchange/btc_bdc',
  BellaCoin_BitCoin: '/exchange/btc_bela',
  Bitstar_BitCoin: '/exchange/btc_bits',
  BlueCoin_BitCoin: '/exchange/btc_blu',
  BonusCoin_BitCoin: '/exchange/btc_bns',
  Bones_BitCoin: '/exchange/btc_bones',
  BoostCoin_BitCoin: '/exchange/btc_bost',
  BitcoinDark_BitCoin: '/exchange/btc_btcd',
  Bitmark_BitCoin: '/exchange/btc_btm',
  BurnerCoin_BitCoin: '/exchange/btc_burn',
  CACHeCoin_BitCoin: '/exchange/btc_cach',
  CryptographicAnomaly_BitCoin: '/exchange/btc_cga',
  Chancecoin_BitCoin: '/exchange/btc_cha',
  CinniCoin_BitCoin: '/exchange/btc_cinni',
  CLAMS_BitCoin: '/exchange/btc_clam',
  ConcealCoin_BitCoin: '/exchange/btc_cnl',
  CNote_BitCoin: '/exchange/btc_cnote',
  CommunityCoin_BitCoin: '/exchange/btc_comm',
  CryptCoin_BitCoin: '/exchange/btc_crypt',
  Curecoin_BitCoin: '/exchange/btc_cure',
  ConspiracyCoin_BitCoin: '/exchange/btc_cyc',
  CarpeDiemCoin_BitCoin: '/exchange/btc_diem',
  DistroCoin_BitCoin: '/exchange/btc_dis',
  Dogecoin_BitCoin: '/exchange/btc_doge',
  DarkCoin_BitCoin: '/exchange/btc_drk',
  DarkCash_BitCoin: '/exchange/btc_drkc',
  DvoraKoin_BitCoin: '/exchange/btc_dvk',
  EBTcoin_BitCoin: '/exchange/btc_ebt',
  ElectronicGulden_BitCoin: '/exchange/btc_efl',
  Einsteinium_BitCoin: '/exchange/btc_emc2',
  Entropycoin_BitCoin: '/exchange/btc_enc',
  ExeCoin_BitCoin: '/exchange/btc_exe',
  Fantomcoin_BitCoin: '/exchange/btc_fcn',
  FlutterCoin_BitCoin: '/exchange/btc_flt',
  FractalCoin_BitCoin: '/exchange/btc_frac',
  FVZCoin_BitCoin: '/exchange/btc_fvz',
  Fuzon_BitCoin: '/exchange/btc_fzn',
  GlobalDenomination_BitCoin: '/exchange/btc_gdn',
  Giarcoin_BitCoin: '/exchange/btc_giar',
  GameleagueCoin_BitCoin: '/exchange/btc_gml',
  GoldEagles_BitCoin: '/exchange/btc_gold',
  GROUPCoin_BitCoin: '/exchange/btc_gpc',
  Gridcoin_BitCoin: '/exchange/btc_grc',
  GroestlCoin_BitCoin: '/exchange/btc_grs',
  GuerillaCoin_BitCoin: '/exchange/btc_gue',
  Hirocoin_BitCoin: '/exchange/btc_hiro',
  Hotcoin_BitCoin: '/exchange/btc_hot',
  HunterCoin_BitCoin: '/exchange/btc_huc',
  IXCoin_BitCoin: '/exchange/btc_ixc',
  jl777hodl_BitCoin: '/exchange/btc_jlh',
  JackpotCoin_BitCoin: '/exchange/btc_jpc',
  KeyCoin_BitCoin: '/exchange/btc_key',
  Logicoin_BitCoin: '/exchange/btc_lgc',
  LeagueCoin_BitCoin: '/exchange/btc_lol',
  LiteCoin_BitCoin: '/exchange/btc_ltc',
  LiteCoinX_BitCoin: '/exchange/btc_ltcx',
  MaidSafeCoin_BitCoin: '/exchange/btc_maid',
  MastiffCoin_BitCoin: '/exchange/btc_mast',
  MonetaVerde_BitCoin: '/exchange/btc_mcn',
  CryptoMETH_BitCoin: '/exchange/btc_meth',
  MillionaireCoin_BitCoin: '/exchange/btc_mil',
  Minerals_BitCoin: '/exchange/btc_min',
  MintCoin_BitCoin: '/exchange/btc_mint',
  MemoryCoin_BitCoin: '/exchange/btc_mmc',
  MiningShares1GH_BitCoin: '/exchange/btc_mns1',
  Monocle_BitCoin: '/exchange/btc_mon',
  microCoin_BitCoin: '/exchange/btc_mrc',
  Marscoin_BitCoin: '/exchange/btc_mrs',
  Mastercoin_BitCoin: '/exchange/btc_msc',
  MyriadCoin_BitCoin: '/exchange/btc_myr',
  N5coin_BitCoin: '/exchange/btc_n5x',
  NAS_BitCoin: '/exchange/btc_nas',
  NautilusCoin_BitCoin: '/exchange/btc_naut',
  Navajo_BitCoin: '/exchange/btc_nav',
  Coin20_BitCoin: '/exchange/btc_nc2',
  NextHorizon_BitCoin: '/exchange/btc_nhz',
  Nanolite_BitCoin: '/exchange/btc_nl',
  NameCoin_BitCoin: '/exchange/btc_nmc',
  NobleCoin_BitCoin: '/exchange/btc_nobl',
  DNotes_BitCoin: '/exchange/btc_note',
  NoirShares_BitCoin: '/exchange/btc_nrs',
  NTX_BitCoin: '/exchange/btc_ntx',
  Nxt_BitCoin: '/exchange/btc_nxt',
  Pawncoin_BitCoin: '/exchange/btc_pawn',
  Pinkcoin_BitCoin: '/exchange/btc_pc',
  NewPiggycoin_BitCoin: '/exchange/btc_piggy',
  ParallaxCoin_BitCoin: '/exchange/btc_plx',
  Premine_BitCoin: '/exchange/btc_pmc',
  PotCoin_BitCoin: '/exchange/btc_pot',
  Peercoin_BitCoin: '/exchange/btc_ppc',
  ProsperCoin_BitCoin: '/exchange/btc_prc',
  Particle_BitCoin: '/exchange/btc_prt',
  Protoshares_BitCoin: '/exchange/btc_pts',
  QubitCoin_BitCoin: '/exchange/btc_q2c',
  Qibuck_BitCoin: '/exchange/btc_qbk',
  QuazarCoin_BitCoin: '/exchange/btc_qcn',
  Qora_BitCoin: '/exchange/btc_qora',
  Rubycoin_BitCoin: '/exchange/btc_rby',
  Reddcoin$Poloniex_BitCoin: '/exchange/btc_redd',
  Riecoin_BitCoin: '/exchange/btc_ric',
  Razor_BitCoin: '/exchange/btc_rzr',
  ShibeCoin_BitCoin: '/exchange/btc_shibe',
  ShopX_BitCoin: '/exchange/btc_shopx',
  Silkcoin$Poloniex_BitCoin: '/exchange/btc_silk',
  SocialCoin_BitCoin: '/exchange/btc_soc',
  SourceCoin_BitCoin: '/exchange/btc_srcc',
  Stellar_BitCoin: '/exchange/btc_str',
  Sync_BitCoin: '/exchange/btc_sync',
  Talkcoin_BitCoin: '/exchange/btc_tac',
  TorCoin_BitCoin: '/exchange/btc_tor',
  TrustPlus_BitCoin: '/exchange/btc_trust',
  URO_BitCoin: '/exchange/btc_uro',
  USDE$Poloniex_BitCoin: '/exchange/btc_usde',
  ViaCoin_BitCoin: '/exchange/btc_via',
  VootCoin_BitCoin: '/exchange/btc_voot',
  VeriCoin_BitCoin: '/exchange/btc_vrc',
  VertCoin_BitCoin: '/exchange/btc_vtc',
  WhiteCoin_BitCoin: '/exchange/btc_wc',
  WorldCoin_BitCoin: '/exchange/btc_wdc',
  InsanityCoin_BitCoin: '/exchange/btc_wolf',
  APICoin_BitCoin: '/exchange/btc_xap',
  BitcoinPlus_BitCoin: '/exchange/btc_xbc',
  XCurrency_BitCoin: '/exchange/btc_xc',
  Counterparty_BitCoin: '/exchange/btc_xcp',
  duckNote_BitCoin: '/exchange/btc_xdn',
  Honorcoin_BitCoin: '/exchange/btc_xhc',
  LibertyCoin_BitCoin: '/exchange/btc_xlb',
  Monero_BitCoin: '/exchange/btc_xmr',
  PrimeCoin_BitCoin: '/exchange/btc_xpm',
  StabilityShares_BitCoin: '/exchange/btc_xsi',
  YACCoin_BitCoin: '/exchange/btc_yacc',
  Yangcoin_BitCoin: '/exchange/btc_yang',
  Yincoin_BitCoin: '/exchange/btc_yin',
  BlackCoin_Monero: '/exchange/xmr_bc',
  Bytecoin$Poloniex_Monero: '/exchange/xmr_bcn',
  BitcoinDark_Monero: '/exchange/xmr_btcd',
  CarpeDiemCoin_Monero: '/exchange/xmr_diem',
  DarkCoin_Monero: '/exchange/xmr_drk',
  InfiniteCoin_Monero: '/exchange/xmr_ifc',
  LiteCoin_Monero: '/exchange/xmr_ltc',
  MaidSafeCoin_Monero: '/exchange/xmr_maid',
  Nxt_Monero: '/exchange/xmr_nxt',
  Qora_Monero: '/exchange/xmr_qora',
  duckNote_Monero: '/exchange/xmr_xdn'
};
