library coin;
import 'package:dyptsy/entity/coin.e.dart';
import 'package:dyptsy/dyptsy.dart';

part 'cryptsy/coin.dart';
part 'poloniex/coin.dart';
part 'coinswap/coin.dart';

final Coin
  BitCoin = new Coin (name: 'BitCoin', shortName: 'BTC'),
  USDollar = new Coin (name: 'USDollar', shortName: 'USD'),
  Dogecoin = new Coin (name: 'Dogecoin', shortName: 'DOGE'),
  DarkCoin = new Coin (name: 'DarkCoin', shortName: 'DRK'),
  FeatherCoin = new Coin (name: 'FeatherCoin', shortName: 'FTC'),
  LiteCoin = new Coin (name: 'LiteCoin', shortName: 'LTC'),
  ReddCoin$Cryptsy = new Coin (name: 'ReddCoin\$Cryptsy', shortName: 'RDD'),
  FourtyTwoCoin = new Coin (name: 'FourtyTwoCoin', shortName: '42'),
  AsiaCoin = new Coin (name: 'AsiaCoin', shortName: 'AC'),
  Aegis = new Coin (name: 'Aegis', shortName: 'AGS'),
  AlphaCoin = new Coin (name: 'AlphaCoin', shortName: 'ALF'),
  AlienCoin = new Coin (name: 'AlienCoin', shortName: 'ALN'),
  AmericanCoin = new Coin (name: 'AmericanCoin', shortName: 'AMC'),
  AnonCoin = new Coin (name: 'AnonCoin', shortName: 'ANC'),
  ApexCoin = new Coin (name: 'ApexCoin', shortName: 'APEX'),
  Argentum = new Coin (name: 'Argentum', shortName: 'ARG'),
  AuroraCoin = new Coin (name: 'AuroraCoin', shortName: 'AUR'),
  BlackCoin = new Coin (name: 'BlackCoin', shortName: 'BC'),
  BattleCoin = new Coin (name: 'BattleCoin', shortName: 'BCX'),
  Benjamins = new Coin (name: 'Benjamins', shortName: 'BEN'),
  Betacoin = new Coin (name: 'Betacoin', shortName: 'BET'),
  BlueCoin = new Coin (name: 'BlueCoin', shortName: 'BLU'),
  BBQCoin = new Coin (name: 'BBQCoin', shortName: 'BQC'),
  BitBar = new Coin (name: 'BitBar', shortName: 'BTB'),
  BitcoinDark = new Coin (name: 'BitcoinDark', shortName: 'BTCD'),
  ByteCoin$Cryptsy = new Coin (name: 'ByteCoin\$Cryptsy', shortName: 'BTE'),
  BitGem = new Coin (name: 'BitGem', shortName: 'BTG'),
  CryptoBuck = new Coin (name: 'CryptoBuck', shortName: 'BUK'),
  CACHeCoin = new Coin (name: 'CACHeCoin', shortName: 'CACH'),
  CAIx = new Coin (name: 'CAIx', shortName: 'CAIx'),
  BottleCaps = new Coin (name: 'BottleCaps', shortName: 'CAP'),
  CashCoin = new Coin (name: 'CashCoin', shortName: 'CASH'),
  CatCoin = new Coin (name: 'CatCoin', shortName: 'CAT'),
  CryptogenicBullion = new Coin (name: 'CryptogenicBullion', shortName: 'CGB'),
  CinniCoin = new Coin (name: 'CinniCoin', shortName: 'CINNI'),
  CloakCoin = new Coin (name: 'CloakCoin', shortName: 'CLOAK'),
  CopperLark = new Coin (name: 'CopperLark', shortName: 'CLR'),
  Cosmoscoin = new Coin (name: 'Cosmoscoin', shortName: 'CMC'),
  CHNCoin = new Coin (name: 'CHNCoin', shortName: 'CNC'),
  ConcealCoin = new Coin (name: 'ConcealCoin', shortName: 'CNL'),
  CommunityCoin = new Coin (name: 'CommunityCoin', shortName: 'COMM'),
  CoolCoin = new Coin (name: 'CoolCoin', shortName: 'COOL'),
  CraftCoin = new Coin (name: 'CraftCoin', shortName: 'CRC'),
  CryptCoin = new Coin (name: 'CryptCoin', shortName: 'CRYPT'),
  CasinoCoin = new Coin (name: 'CasinoCoin', shortName: 'CSC'),
  eMark = new Coin (name: 'eMark', shortName: 'DEM'),
  Digibyte = new Coin (name: 'Digibyte', shortName: 'DGB'),
  DigitalCoin = new Coin (name: 'DigitalCoin', shortName: 'DGC'),
  Diamond = new Coin (name: 'Diamond', shortName: 'DMD'),
  DarkCash = new Coin (name: 'DarkCash', shortName: 'DRKC'),
  DevCoin = new Coin (name: 'DevCoin', shortName: 'DVC'),
  EarthCoin = new Coin (name: 'EarthCoin', shortName: 'EAC'),
  ElaCoin = new Coin (name: 'ElaCoin', shortName: 'ELC'),
  Einsteinium = new Coin (name: 'Einsteinium', shortName: 'EMC2'),
  Emerald = new Coin (name: 'Emerald', shortName: 'EMD'),
  ExeCoin = new Coin (name: 'ExeCoin', shortName: 'EXE'),
  EZCoin = new Coin (name: 'EZCoin', shortName: 'EZC'),
  FireflyCoin = new Coin (name: 'FireflyCoin', shortName: 'FFC'),
  FlutterCoin = new Coin (name: 'FlutterCoin', shortName: 'FLT'),
  FractalCoin = new Coin (name: 'FractalCoin', shortName: 'FRAC'),
  FreiCoin = new Coin (name: 'FreiCoin', shortName: 'FRC'),
  Franko = new Coin (name: 'Franko', shortName: 'FRK'),
  FastCoin = new Coin (name: 'FastCoin', shortName: 'FST'),
  GrandCoin = new Coin (name: 'GrandCoin', shortName: 'GDC'),
  Globalcoin = new Coin (name: 'Globalcoin', shortName: 'GLC'),
  GoldCoin = new Coin (name: 'GoldCoin', shortName: 'GLD'),
  Galaxycoin = new Coin (name: 'Galaxycoin', shortName: 'GLX'),
  GlyphCoin = new Coin (name: 'GlyphCoin', shortName: 'GLYPH'),
  GuerillaCoin = new Coin (name: 'GuerillaCoin', shortName: 'GUE'),
  HoboNickels = new Coin (name: 'HoboNickels', shortName: 'HBN'),
  HunterCoin = new Coin (name: 'HunterCoin', shortName: 'HUC'),
  HeavyCoin = new Coin (name: 'HeavyCoin', shortName: 'HVC'),
  IcebergCoin = new Coin (name: 'IcebergCoin', shortName: 'ICB'),
  InfiniteCoin = new Coin (name: 'InfiniteCoin', shortName: 'IFC'),
  IOCoin = new Coin (name: 'IOCoin', shortName: 'IOC'),
  IXCoin = new Coin (name: 'IXCoin', shortName: 'IXC'),
  JunkCoin = new Coin (name: 'JunkCoin', shortName: 'JKC'),
  JudgeCoin = new Coin (name: 'JudgeCoin', shortName: 'JUDGE'),
  KlondikeCoin = new Coin (name: 'KlondikeCoin', shortName: 'KDC'),
  KeyCoin = new Coin (name: 'KeyCoin', shortName: 'KEY'),
  KrugerCoin = new Coin (name: 'KrugerCoin', shortName: 'KGC'),
  LegendaryCoin = new Coin (name: 'LegendaryCoin', shortName: 'LGD'),
  Lucky7Coin = new Coin (name: 'Lucky7Coin', shortName: 'LK7'),
  LuckyCoin = new Coin (name: 'LuckyCoin', shortName: 'LKY'),
  LiteBar = new Coin (name: 'LiteBar', shortName: 'LTB'),
  LiteCoinX = new Coin (name: 'LiteCoinX', shortName: 'LTCX'),
  LycanCoin = new Coin (name: 'LycanCoin', shortName: 'LYC'),
  MaxCoin = new Coin (name: 'MaxCoin', shortName: 'MAX'),
  MegaCoin = new Coin (name: 'MegaCoin', shortName: 'MEC'),
  Minerals = new Coin (name: 'Minerals', shortName: 'MIN'),
  MintCoin = new Coin (name: 'MintCoin', shortName: 'MINT'),
  MiningContract1 = new Coin (name: 'MiningContract1', shortName: 'MN1'),
  MiningContract2 = new Coin (name: 'MiningContract2', shortName: 'MN2'),
  MinCoin = new Coin (name: 'MinCoin', shortName: 'MNC'),
  MurrayCoin = new Coin (name: 'MurrayCoin', shortName: 'MRY'),
  MyriadCoin = new Coin (name: 'MyriadCoin', shortName: 'MYR'),
  MazaCoin = new Coin (name: 'MazaCoin', shortName: 'MZC'),
  NanoToken = new Coin (name: 'NanoToken', shortName: 'NAN'),
  NautilusCoin = new Coin (name: 'NautilusCoin', shortName: 'NAUT'),
  NavajoCoin = new Coin (name: 'NavajoCoin', shortName: 'NAV'),
  Nibble = new Coin (name: 'Nibble', shortName: 'NBL'),
  NeoCoin = new Coin (name: 'NeoCoin', shortName: 'NEC'),
  Netcoin = new Coin (name: 'Netcoin', shortName: 'NET'),
  NameCoin = new Coin (name: 'NameCoin', shortName: 'NMC'),
  NobleCoin = new Coin (name: 'NobleCoin', shortName: 'NOBL'),
  NoirBits = new Coin (name: 'NoirBits', shortName: 'NRB'),
  NoirShares = new Coin (name: 'NoirShares', shortName: 'NRS'),
  NovaCoin = new Coin (name: 'NovaCoin', shortName: 'NVC'),
  Nxt = new Coin (name: 'Nxt', shortName: 'NXT'),
  NyanCoin = new Coin (name: 'NyanCoin', shortName: 'NYAN'),
  Orbitcoin = new Coin (name: 'Orbitcoin', shortName: 'ORB'),
  OpenSourceCoin = new Coin (name: 'OpenSourceCoin', shortName: 'OSC'),
  PhilosopherStone = new Coin (name: 'PhilosopherStone', shortName: 'PHS'),
  CryptsyPoints = new Coin (name: 'CryptsyPoints', shortName: 'Points'),
  PotCoin = new Coin (name: 'PotCoin', shortName: 'POT'),
  Peercoin = new Coin (name: 'Peercoin', shortName: 'PPC'),
  PseudoCoin = new Coin (name: 'PseudoCoin', shortName: 'PSEUD'),
  BitsharesPTS = new Coin (name: 'BitsharesPTS', shortName: 'PTS'),
  PhoenixCoin = new Coin (name: 'PhoenixCoin', shortName: 'PXC'),
  PayCoin = new Coin (name: 'PayCoin', shortName: 'PYC'),
  Quark = new Coin (name: 'Quark', shortName: 'QRK'),
  RonPaulCoin = new Coin (name: 'RonPaulCoin', shortName: 'RPC'),
  RotoCoin = new Coin (name: 'RotoCoin', shortName: 'RT2'),
  RoyalCoin = new Coin (name: 'RoyalCoin', shortName: 'RYC'),
  Razor = new Coin (name: 'Razor', shortName: 'RZR'),
  SaturnCoinV2 = new Coin (name: 'SaturnCoinV2', shortName: 'SAT2'),
  StableCoin = new Coin (name: 'StableCoin', shortName: 'SBC'),
  SilkCoin$Cryptsy = new Coin (name: 'SilkCoin\$Cryptsy', shortName: 'SC'),
  SaffronCoin = new Coin (name: 'SaffronCoin', shortName: 'SFR'),
  ShieldCoin = new Coin (name: 'ShieldCoin', shortName: 'SHLD'),
  SmartCoin = new Coin (name: 'SmartCoin', shortName: 'SMC'),
  SpainCoin = new Coin (name: 'SpainCoin', shortName: 'SPA'),
  Spots = new Coin (name: 'Spots', shortName: 'SPT'),
  SecureCoin = new Coin (name: 'SecureCoin', shortName: 'SRC'),
  StarCoin = new Coin (name: 'StarCoin', shortName: 'STR'),
  SuperCoin = new Coin (name: 'SuperCoin', shortName: 'SUPER'),
  SexCoin = new Coin (name: 'SexCoin', shortName: 'SXC'),
  Sync = new Coin (name: 'Sync', shortName: 'SYNC'),
  TagCoin = new Coin (name: 'TagCoin', shortName: 'TAG'),
  TakCoin = new Coin (name: 'TakCoin', shortName: 'TAK'),
  TekCoin = new Coin (name: 'TekCoin', shortName: 'TEK'),
  TeslaCoin = new Coin (name: 'TeslaCoin', shortName: 'TES'),
  TigerCoin = new Coin (name: 'TigerCoin', shortName: 'TGC'),
  TorCoin = new Coin (name: 'TorCoin', shortName: 'TOR'),
  TerraCoin = new Coin (name: 'TerraCoin', shortName: 'TRC'),
  UnbreakableCoin = new Coin (name: 'UnbreakableCoin', shortName: 'UNB'),
  Unobtanium = new Coin (name: 'Unobtanium', shortName: 'UNO'),
  URO = new Coin (name: 'URO', shortName: 'URO'),
  USDe$Cryptsy = new Coin (name: 'USDe\$Cryptsy', shortName: 'USDe'),
  UltraCoin = new Coin (name: 'UltraCoin', shortName: 'UTC'),
  ViaCoin = new Coin (name: 'ViaCoin', shortName: 'VIA'),
  VootCoin = new Coin (name: 'VootCoin', shortName: 'VOOT'),
  VeriCoin = new Coin (name: 'VeriCoin', shortName: 'VRC'),
  VertCoin = new Coin (name: 'VertCoin', shortName: 'VTC'),
  WhiteCoin = new Coin (name: 'WhiteCoin', shortName: 'WC'),
  WorldCoin = new Coin (name: 'WorldCoin', shortName: 'WDC'),
  X11Coin = new Coin (name: 'X11Coin', shortName: 'XC'),
  JouleCoin = new Coin (name: 'JouleCoin', shortName: 'XJO'),
  LibertyCoin = new Coin (name: 'LibertyCoin', shortName: 'XLB'),
  PrimeCoin = new Coin (name: 'PrimeCoin', shortName: 'XPM'),
  XXXCoin = new Coin (name: 'XXXCoin', shortName: 'XXX'),
  YaCoin = new Coin (name: 'YaCoin', shortName: 'YAC'),
  YBCoin = new Coin (name: 'YBCoin', shortName: 'YBC'),
  ZcCoin = new Coin (name: 'ZcCoin', shortName: 'ZCC'),
  ZedCoin = new Coin (name: 'ZedCoin', shortName: 'ZED'),
  ZetaCoin = new Coin (name: 'ZetaCoin', shortName: 'ZET'),
  AndroidsTokensV2 = new Coin (name: 'AndroidsTokensV2', shortName: 'ADT'),
  AsicCoin = new Coin (name: 'AsicCoin', shortName: 'ASC'),
  BatCoin = new Coin (name: 'BatCoin', shortName: 'BAT'),
  ColossusCoin = new Coin (name: 'ColossusCoin', shortName: 'COL'),
  CopperBars = new Coin (name: 'CopperBars', shortName: 'CPR'),
  Continuumcoin = new Coin (name: 'Continuumcoin', shortName: 'CTM'),
  Doubloons = new Coin (name: 'Doubloons', shortName: 'DBL'),
  DimeCoin = new Coin (name: 'DimeCoin', shortName: 'DIME'),
  DamaCoin = new Coin (name: 'DamaCoin', shortName: 'DMC'),
  ElephantCoin = new Coin (name: 'ElephantCoin', shortName: 'ELP'),
  FlappyCoin = new Coin (name: 'FlappyCoin', shortName: 'FLAP'),
  FlorinCoin = new Coin (name: 'FlorinCoin', shortName: 'FLO'),
  GameCoin = new Coin (name: 'GameCoin', shortName: 'GME'),
  KarmaCoin = new Coin (name: 'KarmaCoin', shortName: 'KARM'),
  LeafCoin = new Coin (name: 'LeafCoin', shortName: 'LEAF'),
  LottoCoin = new Coin (name: 'LottoCoin', shortName: 'LOT'),
  MemeCoin = new Coin (name: 'MemeCoin', shortName: 'MEM'),
  KittehCoin = new Coin (name: 'KittehCoin', shortName: 'MEOW'),
  MoonCoin = new Coin (name: 'MoonCoin', shortName: 'MOON'),
  MasterCoinHydro = new Coin (name: 'MasterCoinHydro', shortName: 'MST'),
  RabbitCoin = new Coin (name: 'RabbitCoin', shortName: 'RBBT'),
  RedCoin = new Coin (name: 'RedCoin', shortName: 'RED'),
  FedoraCoin = new Coin (name: 'FedoraCoin', shortName: 'TIPS'),
  Tickets = new Coin (name: 'Tickets', shortName: 'TIX'),
  XenCoin = new Coin (name: 'XenCoin', shortName: 'XNC'),
  ZeitCoin = new Coin (name: 'ZeitCoin', shortName: 'ZEIT'),
  OneCRedit = new Coin (name: 'OneCRedit', shortName: '1CR'),
  AppleByte = new Coin (name: 'AppleByte', shortName: 'ABY'),
  Aiden = new Coin (name: 'Aiden', shortName: 'ADN'),
  AEONCoin = new Coin (name: 'AEONCoin', shortName: 'AEON'),
  Aerocoin = new Coin (name: 'Aerocoin', shortName: 'AERO'),
  Axis = new Coin (name: 'Axis', shortName: 'AXIS'),
  BitBlock = new Coin (name: 'BitBlock', shortName: 'BBL'),
  Boolberry = new Coin (name: 'Boolberry', shortName: 'BBR'),
  BTCtalkcoin = new Coin (name: 'BTCtalkcoin', shortName: 'BCC'),
  Bytecoin$Poloniex = new Coin (name: 'Bytecoin\$Poloniex', shortName: 'BCN'),
  BlackDragonCoin = new Coin (name: 'BlackDragonCoin', shortName: 'BDC'),
  BellaCoin = new Coin (name: 'BellaCoin', shortName: 'BELA'),
  Bitstar = new Coin (name: 'Bitstar', shortName: 'BITS'),
  BonusCoin = new Coin (name: 'BonusCoin', shortName: 'BNS'),
  Bones = new Coin (name: 'Bones', shortName: 'BONES'),
  BoostCoin = new Coin (name: 'BoostCoin', shortName: 'BOST'),
  Bitmark = new Coin (name: 'Bitmark', shortName: 'BTM'),
  BurnerCoin = new Coin (name: 'BurnerCoin', shortName: 'BURN'),
  CryptographicAnomaly = new Coin (name: 'CryptographicAnomaly', shortName: 'CGA'),
  Chancecoin = new Coin (name: 'Chancecoin', shortName: 'CHA'),
  CLAMS = new Coin (name: 'CLAMS', shortName: 'CLAM'),
  CNote = new Coin (name: 'CNote', shortName: 'CNOTE'),
  Curecoin = new Coin (name: 'Curecoin', shortName: 'CURE'),
  ConspiracyCoin = new Coin (name: 'ConspiracyCoin', shortName: 'CYC'),
  CarpeDiemCoin = new Coin (name: 'CarpeDiemCoin', shortName: 'DIEM'),
  DistroCoin = new Coin (name: 'DistroCoin', shortName: 'DIS'),
  DvoraKoin = new Coin (name: 'DvoraKoin', shortName: 'DVK'),
  EBTcoin = new Coin (name: 'EBTcoin', shortName: 'EBT'),
  ElectronicGulden = new Coin (name: 'ElectronicGulden', shortName: 'EFL'),
  Entropycoin = new Coin (name: 'Entropycoin', shortName: 'ENC'),
  Fantomcoin = new Coin (name: 'Fantomcoin', shortName: 'FCN'),
  FVZCoin = new Coin (name: 'FVZCoin', shortName: 'FVZ'),
  Fuzon = new Coin (name: 'Fuzon', shortName: 'FZN'),
  GlobalDenomination = new Coin (name: 'GlobalDenomination', shortName: 'GDN'),
  Giarcoin = new Coin (name: 'Giarcoin', shortName: 'GIAR'),
  GameleagueCoin = new Coin (name: 'GameleagueCoin', shortName: 'GML'),
  GoldEagles = new Coin (name: 'GoldEagles', shortName: 'GOLD'),
  GROUPCoin = new Coin (name: 'GROUPCoin', shortName: 'GPC'),
  Gridcoin = new Coin (name: 'Gridcoin', shortName: 'GRC'),
  GroestlCoin = new Coin (name: 'GroestlCoin', shortName: 'GRS'),
  Hirocoin = new Coin (name: 'Hirocoin', shortName: 'HIRO'),
  Hotcoin = new Coin (name: 'Hotcoin', shortName: 'HOT'),
  jl777hodl = new Coin (name: 'jl777hodl', shortName: 'JLH'),
  JackpotCoin = new Coin (name: 'JackpotCoin', shortName: 'JPC'),
  Logicoin = new Coin (name: 'Logicoin', shortName: 'LGC'),
  LeagueCoin = new Coin (name: 'LeagueCoin', shortName: 'LOL'),
  MaidSafeCoin = new Coin (name: 'MaidSafeCoin', shortName: 'MAID'),
  MastiffCoin = new Coin (name: 'MastiffCoin', shortName: 'MAST'),
  MonetaVerde = new Coin (name: 'MonetaVerde', shortName: 'MCN'),
  CryptoMETH = new Coin (name: 'CryptoMETH', shortName: 'METH'),
  MillionaireCoin = new Coin (name: 'MillionaireCoin', shortName: 'MIL'),
  MemoryCoin = new Coin (name: 'MemoryCoin', shortName: 'MMC'),
  MiningShares1GH = new Coin (name: 'MiningShares1GH', shortName: 'MNS1'),
  Monocle = new Coin (name: 'Monocle', shortName: 'MON'),
  microCoin = new Coin (name: 'microCoin', shortName: 'MRC'),
  Marscoin = new Coin (name: 'Marscoin', shortName: 'MRS'),
  Mastercoin = new Coin (name: 'Mastercoin', shortName: 'MSC'),
  N5coin = new Coin (name: 'N5coin', shortName: 'N5X'),
  NAS = new Coin (name: 'NAS', shortName: 'NAS'),
  Navajo = new Coin (name: 'Navajo', shortName: 'NAV'),
  Coin20 = new Coin (name: 'Coin20', shortName: 'NC2'),
  NextHorizon = new Coin (name: 'NextHorizon', shortName: 'NHZ'),
  Nanolite = new Coin (name: 'Nanolite', shortName: 'NL'),
  DNotes = new Coin (name: 'DNotes', shortName: 'NOTE'),
  NTX = new Coin (name: 'NTX', shortName: 'NTX'),
  Pawncoin = new Coin (name: 'Pawncoin', shortName: 'PAWN'),
  Pinkcoin = new Coin (name: 'Pinkcoin', shortName: 'PC'),
  NewPiggycoin = new Coin (name: 'NewPiggycoin', shortName: 'PIGGY'),
  ParallaxCoin = new Coin (name: 'ParallaxCoin', shortName: 'PLX'),
  Premine = new Coin (name: 'Premine', shortName: 'PMC'),
  ProsperCoin = new Coin (name: 'ProsperCoin', shortName: 'PRC'),
  Particle = new Coin (name: 'Particle', shortName: 'PRT'),
  Protoshares = new Coin (name: 'Protoshares', shortName: 'PTS'),
  QubitCoin = new Coin (name: 'QubitCoin', shortName: 'Q2C'),
  Qibuck = new Coin (name: 'Qibuck', shortName: 'QBK'),
  QuazarCoin = new Coin (name: 'QuazarCoin', shortName: 'QCN'),
  Qora = new Coin (name: 'Qora', shortName: 'QORA'),
  Rubycoin = new Coin (name: 'Rubycoin', shortName: 'RBY'),
  Reddcoin$Poloniex = new Coin (name: 'Reddcoin\$Poloniex', shortName: 'REDD'),
  Riecoin = new Coin (name: 'Riecoin', shortName: 'RIC'),
  ShibeCoin = new Coin (name: 'ShibeCoin', shortName: 'SHIBE'),
  ShopX = new Coin (name: 'ShopX', shortName: 'SHOPX'),
  Silkcoin$Poloniex = new Coin (name: 'Silkcoin\$Poloniex', shortName: 'SILK'),
  SocialCoin = new Coin (name: 'SocialCoin', shortName: 'SOC'),
  SourceCoin = new Coin (name: 'SourceCoin', shortName: 'SRCC'),
  Stellar = new Coin (name: 'Stellar', shortName: 'STR'),
  Talkcoin = new Coin (name: 'Talkcoin', shortName: 'TAC'),
  TrustPlus = new Coin (name: 'TrustPlus', shortName: 'TRUST'),
  USDE$Poloniex = new Coin (name: 'USDE\$Poloniex', shortName: 'USDE'),
  InsanityCoin = new Coin (name: 'InsanityCoin', shortName: 'WOLF'),
  APICoin = new Coin (name: 'APICoin', shortName: 'XAP'),
  BitcoinPlus = new Coin (name: 'BitcoinPlus', shortName: 'XBC'),
  XCurrency = new Coin (name: 'XCurrency', shortName: 'XC'),
  Counterparty = new Coin (name: 'Counterparty', shortName: 'XCP'),
  duckNote = new Coin (name: 'duckNote', shortName: 'XDN'),
  Honorcoin = new Coin (name: 'Honorcoin', shortName: 'XHC'),
  Monero = new Coin (name: 'Monero', shortName: 'XMR'),
  StabilityShares = new Coin (name: 'StabilityShares', shortName: 'XSI'),
  YACCoin = new Coin (name: 'YACCoin', shortName: 'YACC'),
  Yangcoin = new Coin (name: 'Yangcoin', shortName: 'YANG'),
  Yincoin = new Coin (name: 'Yincoin', shortName: 'YIN'),
  SixtySixCoin = new Coin (name: 'SixtySixCoin', shortName: '66'),
  Aidbit = new Coin (name: 'Aidbit', shortName: 'AID'),
  Ascentcoin = new Coin (name: 'Ascentcoin', shortName: 'ASCE'),
  Buylatercoin = new Coin (name: 'Buylatercoin', shortName: 'BLTR'),
  Blazecoin = new Coin (name: 'Blazecoin', shortName: 'BLZ'),
  Bitmoney = new Coin (name: 'Bitmoney', shortName: 'BMY'),
  Borgcoin = new Coin (name: 'Borgcoin', shortName: 'BORG'),
  GlobalBoost = new Coin (name: 'GlobalBoost', shortName: 'BST'),
  Banksycoin = new Coin (name: 'Banksycoin', shortName: 'BSY'),
  CaiShen = new Coin (name: 'CaiShen', shortName: 'CAIx'),
  CAPTcoin = new Coin (name: 'CAPTcoin', shortName: 'CAPT'),
  Chakracoin = new Coin (name: 'Chakracoin', shortName: 'CKC'),
  Cloak = new Coin (name: 'Cloak', shortName: 'CLOAK'),
  Compasscoin = new Coin (name: 'Compasscoin', shortName: 'CPC'),
  Compucoin = new Coin (name: 'Compucoin', shortName: 'CPN'),
  Credits = new Coin (name: 'Credits', shortName: 'CRD'),
  EmbargoCoin = new Coin (name: 'EmbargoCoin', shortName: 'EBG'),
  Fusecoin = new Coin (name: 'Fusecoin', shortName: 'FUSE'),
  GunCoin = new Coin (name: 'GunCoin', shortName: 'GUN'),
  Hyperstake = new Coin (name: 'Hyperstake', shortName: 'HYP'),
  ImperialcoinIMP = new Coin (name: 'ImperialcoinIMP', shortName: 'IMP'),
  ImperialcoinIPC = new Coin (name: 'ImperialcoinIPC', shortName: 'IPC'),
  Koolio = new Coin (name: 'Koolio', shortName: 'KOOL'),
  KryptKoin = new Coin (name: 'KryptKoin', shortName: 'KTK'),
  LATIUM = new Coin (name: 'LATIUM', shortName: 'LAT'),
  ElectronicLIRA = new Coin (name: 'ElectronicLIRA', shortName: 'LIRE'),
  Latinum = new Coin (name: 'Latinum', shortName: 'LTM'),
  Multicoin = new Coin (name: 'Multicoin', shortName: 'MC'),
  PeoplesCurrency = new Coin (name: 'PeoplesCurrency', shortName: 'PPL'),
  PayProCoin = new Coin (name: 'PayProCoin', shortName: 'PRO'),
  PureCoin = new Coin (name: 'PureCoin', shortName: 'PURE'),
  RobotSexNickels = new Coin (name: 'RobotSexNickels', shortName: 'RSN'),
  Shadowcoin = new Coin (name: 'Shadowcoin', shortName: 'SDC'),
  Shinycoin = new Coin (name: 'Shinycoin', shortName: 'SHC'),
  Shibe = new Coin (name: 'Shibe', shortName: 'SHIBE'),
  STLcoin = new Coin (name: 'STLcoin', shortName: 'STL'),
  VirtualminingCoin = new Coin (name: 'VirtualminingCoin', shortName: 'VMC'),
  GoldReserve = new Coin (name: 'GoldReserve', shortName: 'XGR'),
  YellowCoin = new Coin (name: 'YellowCoin', shortName: 'YC'),
  ActiveCoin = new Coin (name: 'ActiveCoin', shortName: 'ACT'),
  Bunnycoin = new Coin (name: 'Bunnycoin', shortName: 'BUNNY'),
  CornerstoneCoin = new Coin (name: 'CornerstoneCoin', shortName: 'CCX'),
  Dojecoin = new Coin (name: 'Dojecoin', shortName: 'DOJE'),
  Hobbitcoin = new Coin (name: 'Hobbitcoin', shortName: 'HBC'),
  HTMLcoin = new Coin (name: 'HTMLcoin', shortName: 'HTML');

final List<Coin> AllCoins = <Coin>[
  BitCoin,
  USDollar,
  Dogecoin,
  DarkCoin,
  FeatherCoin,
  LiteCoin,
  ReddCoin$Cryptsy,
  FourtyTwoCoin,
  AsiaCoin,
  Aegis,
  AlphaCoin,
  AlienCoin,
  AmericanCoin,
  AnonCoin,
  ApexCoin,
  Argentum,
  AuroraCoin,
  BlackCoin,
  BattleCoin,
  Benjamins,
  Betacoin,
  BlueCoin,
  BBQCoin,
  BitBar,
  BitcoinDark,
  ByteCoin$Cryptsy,
  BitGem,
  CryptoBuck,
  CACHeCoin,
  CAIx,
  BottleCaps,
  CashCoin,
  CatCoin,
  CryptogenicBullion,
  CinniCoin,
  CloakCoin,
  CopperLark,
  Cosmoscoin,
  CHNCoin,
  ConcealCoin,
  CommunityCoin,
  CoolCoin,
  CraftCoin,
  CryptCoin,
  CasinoCoin,
  eMark,
  Digibyte,
  DigitalCoin,
  Diamond,
  DarkCash,
  DevCoin,
  EarthCoin,
  ElaCoin,
  Einsteinium,
  Emerald,
  ExeCoin,
  EZCoin,
  FireflyCoin,
  FlutterCoin,
  FractalCoin,
  FreiCoin,
  Franko,
  FastCoin,
  GrandCoin,
  Globalcoin,
  GoldCoin,
  Galaxycoin,
  GlyphCoin,
  GuerillaCoin,
  HoboNickels,
  HunterCoin,
  HeavyCoin,
  IcebergCoin,
  InfiniteCoin,
  IOCoin,
  IXCoin,
  JunkCoin,
  JudgeCoin,
  KlondikeCoin,
  KeyCoin,
  KrugerCoin,
  LegendaryCoin,
  Lucky7Coin,
  LuckyCoin,
  LiteBar,
  LiteCoinX,
  LycanCoin,
  MaxCoin,
  MegaCoin,
  Minerals,
  MintCoin,
  MiningContract1,
  MiningContract2,
  MinCoin,
  MurrayCoin,
  MyriadCoin,
  MazaCoin,
  NanoToken,
  NautilusCoin,
  NavajoCoin,
  Nibble,
  NeoCoin,
  Netcoin,
  NameCoin,
  NobleCoin,
  NoirBits,
  NoirShares,
  NovaCoin,
  Nxt,
  NyanCoin,
  Orbitcoin,
  OpenSourceCoin,
  PhilosopherStone,
  CryptsyPoints,
  PotCoin,
  Peercoin,
  PseudoCoin,
  BitsharesPTS,
  PhoenixCoin,
  PayCoin,
  Quark,
  RonPaulCoin,
  RotoCoin,
  RoyalCoin,
  Razor,
  SaturnCoinV2,
  StableCoin,
  SilkCoin$Cryptsy,
  SaffronCoin,
  ShieldCoin,
  SmartCoin,
  SpainCoin,
  Spots,
  SecureCoin,
  StarCoin,
  SuperCoin,
  SexCoin,
  Sync,
  TagCoin,
  TakCoin,
  TekCoin,
  TeslaCoin,
  TigerCoin,
  TorCoin,
  TerraCoin,
  UnbreakableCoin,
  Unobtanium,
  URO,
  USDe$Cryptsy,
  UltraCoin,
  ViaCoin,
  VootCoin,
  VeriCoin,
  VertCoin,
  WhiteCoin,
  WorldCoin,
  X11Coin,
  JouleCoin,
  LibertyCoin,
  PrimeCoin,
  XXXCoin,
  YaCoin,
  YBCoin,
  ZcCoin,
  ZedCoin,
  ZetaCoin,
  AndroidsTokensV2,
  AsicCoin,
  BatCoin,
  ColossusCoin,
  CopperBars,
  Continuumcoin,
  Doubloons,
  DimeCoin,
  DamaCoin,
  ElephantCoin,
  FlappyCoin,
  FlorinCoin,
  GameCoin,
  KarmaCoin,
  LeafCoin,
  LottoCoin,
  MemeCoin,
  KittehCoin,
  MoonCoin,
  MasterCoinHydro,
  RabbitCoin,
  RedCoin,
  FedoraCoin,
  Tickets,
  XenCoin,
  ZeitCoin,
  OneCRedit,
  AppleByte,
  Aiden,
  AEONCoin,
  Aerocoin,
  Axis,
  BitBlock,
  Boolberry,
  BTCtalkcoin,
  Bytecoin$Poloniex,
  BlackDragonCoin,
  BellaCoin,
  Bitstar,
  BonusCoin,
  Bones,
  BoostCoin,
  Bitmark,
  BurnerCoin,
  CryptographicAnomaly,
  Chancecoin,
  CLAMS,
  CNote,
  Curecoin,
  ConspiracyCoin,
  CarpeDiemCoin,
  DistroCoin,
  DvoraKoin,
  EBTcoin,
  ElectronicGulden,
  Entropycoin,
  Fantomcoin,
  FVZCoin,
  Fuzon,
  GlobalDenomination,
  Giarcoin,
  GameleagueCoin,
  GoldEagles,
  GROUPCoin,
  Gridcoin,
  GroestlCoin,
  Hirocoin,
  Hotcoin,
  jl777hodl,
  JackpotCoin,
  Logicoin,
  LeagueCoin,
  MaidSafeCoin,
  MastiffCoin,
  MonetaVerde,
  CryptoMETH,
  MillionaireCoin,
  MemoryCoin,
  MiningShares1GH,
  Monocle,
  microCoin,
  Marscoin,
  Mastercoin,
  N5coin,
  NAS,
  Navajo,
  Coin20,
  NextHorizon,
  Nanolite,
  DNotes,
  NTX,
  Pawncoin,
  Pinkcoin,
  NewPiggycoin,
  ParallaxCoin,
  Premine,
  ProsperCoin,
  Particle,
  Protoshares,
  QubitCoin,
  Qibuck,
  QuazarCoin,
  Qora,
  Rubycoin,
  Reddcoin$Poloniex,
  Riecoin,
  ShibeCoin,
  ShopX,
  Silkcoin$Poloniex,
  SocialCoin,
  SourceCoin,
  Stellar,
  Talkcoin,
  TrustPlus,
  USDE$Poloniex,
  InsanityCoin,
  APICoin,
  BitcoinPlus,
  XCurrency,
  Counterparty,
  duckNote,
  Honorcoin,
  Monero,
  StabilityShares,
  YACCoin,
  Yangcoin,
  Yincoin,
  SixtySixCoin,
  Aidbit,
  Ascentcoin,
  Buylatercoin,
  Blazecoin,
  Bitmoney,
  Borgcoin,
  GlobalBoost,
  Banksycoin,
  CaiShen,
  CAPTcoin,
  Chakracoin,
  Cloak,
  Compasscoin,
  Compucoin,
  Credits,
  EmbargoCoin,
  Fusecoin,
  GunCoin,
  Hyperstake,
  ImperialcoinIMP,
  ImperialcoinIPC,
  Koolio,
  KryptKoin,
  LATIUM,
  ElectronicLIRA,
  Latinum,
  Multicoin,
  PeoplesCurrency,
  PayProCoin,
  PureCoin,
  RobotSexNickels,
  Shadowcoin,
  Shinycoin,
  Shibe,
  STLcoin,
  VirtualminingCoin,
  GoldReserve,
  YellowCoin,
  ActiveCoin,
  Bunnycoin,
  CornerstoneCoin,
  Dojecoin,
  Hobbitcoin,
  HTMLcoin
];

final Pair
  BitCoin_USDollar = new Pair (BitCoin, USDollar),
  Dogecoin_USDollar = new Pair (Dogecoin, USDollar),
  DarkCoin_USDollar = new Pair (DarkCoin, USDollar),
  FeatherCoin_USDollar = new Pair (FeatherCoin, USDollar),
  LiteCoin_USDollar = new Pair (LiteCoin, USDollar),
  ReddCoin$Cryptsy_USDollar = new Pair (ReddCoin$Cryptsy, USDollar),
  FourtyTwoCoin_BitCoin = new Pair (FourtyTwoCoin, BitCoin),
  AsiaCoin_BitCoin = new Pair (AsiaCoin, BitCoin),
  Aegis_BitCoin = new Pair (Aegis, BitCoin),
  AlphaCoin_BitCoin = new Pair (AlphaCoin, BitCoin),
  AlienCoin_BitCoin = new Pair (AlienCoin, BitCoin),
  AmericanCoin_BitCoin = new Pair (AmericanCoin, BitCoin),
  AnonCoin_BitCoin = new Pair (AnonCoin, BitCoin),
  ApexCoin_BitCoin = new Pair (ApexCoin, BitCoin),
  Argentum_BitCoin = new Pair (Argentum, BitCoin),
  AuroraCoin_BitCoin = new Pair (AuroraCoin, BitCoin),
  BlackCoin_BitCoin = new Pair (BlackCoin, BitCoin),
  BattleCoin_BitCoin = new Pair (BattleCoin, BitCoin),
  Benjamins_BitCoin = new Pair (Benjamins, BitCoin),
  Betacoin_BitCoin = new Pair (Betacoin, BitCoin),
  BlueCoin_BitCoin = new Pair (BlueCoin, BitCoin),
  BBQCoin_BitCoin = new Pair (BBQCoin, BitCoin),
  BitBar_BitCoin = new Pair (BitBar, BitCoin),
  BitcoinDark_BitCoin = new Pair (BitcoinDark, BitCoin),
  ByteCoin$Cryptsy_BitCoin = new Pair (ByteCoin$Cryptsy, BitCoin),
  BitGem_BitCoin = new Pair (BitGem, BitCoin),
  CryptoBuck_BitCoin = new Pair (CryptoBuck, BitCoin),
  CACHeCoin_BitCoin = new Pair (CACHeCoin, BitCoin),
  CAIx_BitCoin = new Pair (CAIx, BitCoin),
  BottleCaps_BitCoin = new Pair (BottleCaps, BitCoin),
  CashCoin_BitCoin = new Pair (CashCoin, BitCoin),
  CatCoin_BitCoin = new Pair (CatCoin, BitCoin),
  CryptogenicBullion_BitCoin = new Pair (CryptogenicBullion, BitCoin),
  CinniCoin_BitCoin = new Pair (CinniCoin, BitCoin),
  CloakCoin_BitCoin = new Pair (CloakCoin, BitCoin),
  CopperLark_BitCoin = new Pair (CopperLark, BitCoin),
  Cosmoscoin_BitCoin = new Pair (Cosmoscoin, BitCoin),
  CHNCoin_BitCoin = new Pair (CHNCoin, BitCoin),
  ConcealCoin_BitCoin = new Pair (ConcealCoin, BitCoin),
  CommunityCoin_BitCoin = new Pair (CommunityCoin, BitCoin),
  CoolCoin_BitCoin = new Pair (CoolCoin, BitCoin),
  CraftCoin_BitCoin = new Pair (CraftCoin, BitCoin),
  CryptCoin_BitCoin = new Pair (CryptCoin, BitCoin),
  CasinoCoin_BitCoin = new Pair (CasinoCoin, BitCoin),
  eMark_BitCoin = new Pair (eMark, BitCoin),
  Digibyte_BitCoin = new Pair (Digibyte, BitCoin),
  DigitalCoin_BitCoin = new Pair (DigitalCoin, BitCoin),
  Diamond_BitCoin = new Pair (Diamond, BitCoin),
  Dogecoin_BitCoin = new Pair (Dogecoin, BitCoin),
  DarkCoin_BitCoin = new Pair (DarkCoin, BitCoin),
  DarkCash_BitCoin = new Pair (DarkCash, BitCoin),
  DevCoin_BitCoin = new Pair (DevCoin, BitCoin),
  EarthCoin_BitCoin = new Pair (EarthCoin, BitCoin),
  ElaCoin_BitCoin = new Pair (ElaCoin, BitCoin),
  Einsteinium_BitCoin = new Pair (Einsteinium, BitCoin),
  Emerald_BitCoin = new Pair (Emerald, BitCoin),
  ExeCoin_BitCoin = new Pair (ExeCoin, BitCoin),
  EZCoin_BitCoin = new Pair (EZCoin, BitCoin),
  FireflyCoin_BitCoin = new Pair (FireflyCoin, BitCoin),
  FlutterCoin_BitCoin = new Pair (FlutterCoin, BitCoin),
  FractalCoin_BitCoin = new Pair (FractalCoin, BitCoin),
  FreiCoin_BitCoin = new Pair (FreiCoin, BitCoin),
  Franko_BitCoin = new Pair (Franko, BitCoin),
  FastCoin_BitCoin = new Pair (FastCoin, BitCoin),
  FeatherCoin_BitCoin = new Pair (FeatherCoin, BitCoin),
  GrandCoin_BitCoin = new Pair (GrandCoin, BitCoin),
  Globalcoin_BitCoin = new Pair (Globalcoin, BitCoin),
  GoldCoin_BitCoin = new Pair (GoldCoin, BitCoin),
  Galaxycoin_BitCoin = new Pair (Galaxycoin, BitCoin),
  GlyphCoin_BitCoin = new Pair (GlyphCoin, BitCoin),
  GuerillaCoin_BitCoin = new Pair (GuerillaCoin, BitCoin),
  HoboNickels_BitCoin = new Pair (HoboNickels, BitCoin),
  HunterCoin_BitCoin = new Pair (HunterCoin, BitCoin),
  HeavyCoin_BitCoin = new Pair (HeavyCoin, BitCoin),
  IcebergCoin_BitCoin = new Pair (IcebergCoin, BitCoin),
  InfiniteCoin_BitCoin = new Pair (InfiniteCoin, BitCoin),
  IOCoin_BitCoin = new Pair (IOCoin, BitCoin),
  IXCoin_BitCoin = new Pair (IXCoin, BitCoin),
  JunkCoin_BitCoin = new Pair (JunkCoin, BitCoin),
  JudgeCoin_BitCoin = new Pair (JudgeCoin, BitCoin),
  KlondikeCoin_BitCoin = new Pair (KlondikeCoin, BitCoin),
  KeyCoin_BitCoin = new Pair (KeyCoin, BitCoin),
  KrugerCoin_BitCoin = new Pair (KrugerCoin, BitCoin),
  LegendaryCoin_BitCoin = new Pair (LegendaryCoin, BitCoin),
  Lucky7Coin_BitCoin = new Pair (Lucky7Coin, BitCoin),
  LuckyCoin_BitCoin = new Pair (LuckyCoin, BitCoin),
  LiteBar_BitCoin = new Pair (LiteBar, BitCoin),
  LiteCoin_BitCoin = new Pair (LiteCoin, BitCoin),
  LiteCoinX_BitCoin = new Pair (LiteCoinX, BitCoin),
  LycanCoin_BitCoin = new Pair (LycanCoin, BitCoin),
  MaxCoin_BitCoin = new Pair (MaxCoin, BitCoin),
  MegaCoin_BitCoin = new Pair (MegaCoin, BitCoin),
  Minerals_BitCoin = new Pair (Minerals, BitCoin),
  MintCoin_BitCoin = new Pair (MintCoin, BitCoin),
  MiningContract1_BitCoin = new Pair (MiningContract1, BitCoin),
  MiningContract2_BitCoin = new Pair (MiningContract2, BitCoin),
  MinCoin_BitCoin = new Pair (MinCoin, BitCoin),
  MurrayCoin_BitCoin = new Pair (MurrayCoin, BitCoin),
  MyriadCoin_BitCoin = new Pair (MyriadCoin, BitCoin),
  MazaCoin_BitCoin = new Pair (MazaCoin, BitCoin),
  NanoToken_BitCoin = new Pair (NanoToken, BitCoin),
  NautilusCoin_BitCoin = new Pair (NautilusCoin, BitCoin),
  NavajoCoin_BitCoin = new Pair (NavajoCoin, BitCoin),
  Nibble_BitCoin = new Pair (Nibble, BitCoin),
  NeoCoin_BitCoin = new Pair (NeoCoin, BitCoin),
  Netcoin_BitCoin = new Pair (Netcoin, BitCoin),
  NameCoin_BitCoin = new Pair (NameCoin, BitCoin),
  NobleCoin_BitCoin = new Pair (NobleCoin, BitCoin),
  NoirBits_BitCoin = new Pair (NoirBits, BitCoin),
  NoirShares_BitCoin = new Pair (NoirShares, BitCoin),
  NovaCoin_BitCoin = new Pair (NovaCoin, BitCoin),
  Nxt_BitCoin = new Pair (Nxt, BitCoin),
  NyanCoin_BitCoin = new Pair (NyanCoin, BitCoin),
  Orbitcoin_BitCoin = new Pair (Orbitcoin, BitCoin),
  OpenSourceCoin_BitCoin = new Pair (OpenSourceCoin, BitCoin),
  PhilosopherStone_BitCoin = new Pair (PhilosopherStone, BitCoin),
  CryptsyPoints_BitCoin = new Pair (CryptsyPoints, BitCoin),
  PotCoin_BitCoin = new Pair (PotCoin, BitCoin),
  Peercoin_BitCoin = new Pair (Peercoin, BitCoin),
  PseudoCoin_BitCoin = new Pair (PseudoCoin, BitCoin),
  BitsharesPTS_BitCoin = new Pair (BitsharesPTS, BitCoin),
  PhoenixCoin_BitCoin = new Pair (PhoenixCoin, BitCoin),
  PayCoin_BitCoin = new Pair (PayCoin, BitCoin),
  Quark_BitCoin = new Pair (Quark, BitCoin),
  ReddCoin$Cryptsy_BitCoin = new Pair (ReddCoin$Cryptsy, BitCoin),
  RonPaulCoin_BitCoin = new Pair (RonPaulCoin, BitCoin),
  RotoCoin_BitCoin = new Pair (RotoCoin, BitCoin),
  RoyalCoin_BitCoin = new Pair (RoyalCoin, BitCoin),
  Razor_BitCoin = new Pair (Razor, BitCoin),
  SaturnCoinV2_BitCoin = new Pair (SaturnCoinV2, BitCoin),
  StableCoin_BitCoin = new Pair (StableCoin, BitCoin),
  SilkCoin$Cryptsy_BitCoin = new Pair (SilkCoin$Cryptsy, BitCoin),
  SaffronCoin_BitCoin = new Pair (SaffronCoin, BitCoin),
  ShieldCoin_BitCoin = new Pair (ShieldCoin, BitCoin),
  SmartCoin_BitCoin = new Pair (SmartCoin, BitCoin),
  SpainCoin_BitCoin = new Pair (SpainCoin, BitCoin),
  Spots_BitCoin = new Pair (Spots, BitCoin),
  SecureCoin_BitCoin = new Pair (SecureCoin, BitCoin),
  StarCoin_BitCoin = new Pair (StarCoin, BitCoin),
  SuperCoin_BitCoin = new Pair (SuperCoin, BitCoin),
  SexCoin_BitCoin = new Pair (SexCoin, BitCoin),
  Sync_BitCoin = new Pair (Sync, BitCoin),
  TagCoin_BitCoin = new Pair (TagCoin, BitCoin),
  TakCoin_BitCoin = new Pair (TakCoin, BitCoin),
  TekCoin_BitCoin = new Pair (TekCoin, BitCoin),
  TeslaCoin_BitCoin = new Pair (TeslaCoin, BitCoin),
  TigerCoin_BitCoin = new Pair (TigerCoin, BitCoin),
  TorCoin_BitCoin = new Pair (TorCoin, BitCoin),
  TerraCoin_BitCoin = new Pair (TerraCoin, BitCoin),
  UnbreakableCoin_BitCoin = new Pair (UnbreakableCoin, BitCoin),
  Unobtanium_BitCoin = new Pair (Unobtanium, BitCoin),
  URO_BitCoin = new Pair (URO, BitCoin),
  USDe$Cryptsy_BitCoin = new Pair (USDe$Cryptsy, BitCoin),
  UltraCoin_BitCoin = new Pair (UltraCoin, BitCoin),
  ViaCoin_BitCoin = new Pair (ViaCoin, BitCoin),
  VootCoin_BitCoin = new Pair (VootCoin, BitCoin),
  VeriCoin_BitCoin = new Pair (VeriCoin, BitCoin),
  VertCoin_BitCoin = new Pair (VertCoin, BitCoin),
  WhiteCoin_BitCoin = new Pair (WhiteCoin, BitCoin),
  WorldCoin_BitCoin = new Pair (WorldCoin, BitCoin),
  X11Coin_BitCoin = new Pair (X11Coin, BitCoin),
  JouleCoin_BitCoin = new Pair (JouleCoin, BitCoin),
  LibertyCoin_BitCoin = new Pair (LibertyCoin, BitCoin),
  PrimeCoin_BitCoin = new Pair (PrimeCoin, BitCoin),
  XXXCoin_BitCoin = new Pair (XXXCoin, BitCoin),
  YaCoin_BitCoin = new Pair (YaCoin, BitCoin),
  YBCoin_BitCoin = new Pair (YBCoin, BitCoin),
  ZcCoin_BitCoin = new Pair (ZcCoin, BitCoin),
  ZedCoin_BitCoin = new Pair (ZedCoin, BitCoin),
  ZetaCoin_BitCoin = new Pair (ZetaCoin, BitCoin),
  AndroidsTokensV2_LiteCoin = new Pair (AndroidsTokensV2, LiteCoin),
  AnonCoin_LiteCoin = new Pair (AnonCoin, LiteCoin),
  AsicCoin_LiteCoin = new Pair (AsicCoin, LiteCoin),
  AuroraCoin_LiteCoin = new Pair (AuroraCoin, LiteCoin),
  BatCoin_LiteCoin = new Pair (BatCoin, LiteCoin),
  BlackCoin_LiteCoin = new Pair (BlackCoin, LiteCoin),
  CryptogenicBullion_LiteCoin = new Pair (CryptogenicBullion, LiteCoin),
  CloakCoin_LiteCoin = new Pair (CloakCoin, LiteCoin),
  CHNCoin_LiteCoin = new Pair (CHNCoin, LiteCoin),
  ColossusCoin_LiteCoin = new Pair (ColossusCoin, LiteCoin),
  CopperBars_LiteCoin = new Pair (CopperBars, LiteCoin),
  CryptCoin_LiteCoin = new Pair (CryptCoin, LiteCoin),
  Continuumcoin_LiteCoin = new Pair (Continuumcoin, LiteCoin),
  Doubloons_LiteCoin = new Pair (Doubloons, LiteCoin),
  DigitalCoin_LiteCoin = new Pair (DigitalCoin, LiteCoin),
  DimeCoin_LiteCoin = new Pair (DimeCoin, LiteCoin),
  DamaCoin_LiteCoin = new Pair (DamaCoin, LiteCoin),
  Dogecoin_LiteCoin = new Pair (Dogecoin, LiteCoin),
  DarkCoin_LiteCoin = new Pair (DarkCoin, LiteCoin),
  DevCoin_LiteCoin = new Pair (DevCoin, LiteCoin),
  EarthCoin_LiteCoin = new Pair (EarthCoin, LiteCoin),
  ElephantCoin_LiteCoin = new Pair (ElephantCoin, LiteCoin),
  EZCoin_LiteCoin = new Pair (EZCoin, LiteCoin),
  FlappyCoin_LiteCoin = new Pair (FlappyCoin, LiteCoin),
  FlorinCoin_LiteCoin = new Pair (FlorinCoin, LiteCoin),
  Franko_LiteCoin = new Pair (Franko, LiteCoin),
  FastCoin_LiteCoin = new Pair (FastCoin, LiteCoin),
  FeatherCoin_LiteCoin = new Pair (FeatherCoin, LiteCoin),
  GoldCoin_LiteCoin = new Pair (GoldCoin, LiteCoin),
  GlyphCoin_LiteCoin = new Pair (GlyphCoin, LiteCoin),
  GameCoin_LiteCoin = new Pair (GameCoin, LiteCoin),
  GuerillaCoin_LiteCoin = new Pair (GuerillaCoin, LiteCoin),
  InfiniteCoin_LiteCoin = new Pair (InfiniteCoin, LiteCoin),
  KarmaCoin_LiteCoin = new Pair (KarmaCoin, LiteCoin),
  LeafCoin_LiteCoin = new Pair (LeafCoin, LiteCoin),
  LottoCoin_LiteCoin = new Pair (LottoCoin, LiteCoin),
  LiteCoinX_LiteCoin = new Pair (LiteCoinX, LiteCoin),
  MaxCoin_LiteCoin = new Pair (MaxCoin, LiteCoin),
  MegaCoin_LiteCoin = new Pair (MegaCoin, LiteCoin),
  MemeCoin_LiteCoin = new Pair (MemeCoin, LiteCoin),
  KittehCoin_LiteCoin = new Pair (KittehCoin, LiteCoin),
  MoonCoin_LiteCoin = new Pair (MoonCoin, LiteCoin),
  MasterCoinHydro_LiteCoin = new Pair (MasterCoinHydro, LiteCoin),
  Netcoin_LiteCoin = new Pair (Netcoin, LiteCoin),
  Nxt_LiteCoin = new Pair (Nxt, LiteCoin),
  NyanCoin_LiteCoin = new Pair (NyanCoin, LiteCoin),
  Peercoin_LiteCoin = new Pair (Peercoin, LiteCoin),
  PhoenixCoin_LiteCoin = new Pair (PhoenixCoin, LiteCoin),
  Quark_LiteCoin = new Pair (Quark, LiteCoin),
  RabbitCoin_LiteCoin = new Pair (RabbitCoin, LiteCoin),
  ReddCoin$Cryptsy_LiteCoin = new Pair (ReddCoin$Cryptsy, LiteCoin),
  RedCoin_LiteCoin = new Pair (RedCoin, LiteCoin),
  Razor_LiteCoin = new Pair (Razor, LiteCoin),
  StableCoin_LiteCoin = new Pair (StableCoin, LiteCoin),
  SuperCoin_LiteCoin = new Pair (SuperCoin, LiteCoin),
  SexCoin_LiteCoin = new Pair (SexCoin, LiteCoin),
  TeslaCoin_LiteCoin = new Pair (TeslaCoin, LiteCoin),
  FedoraCoin_LiteCoin = new Pair (FedoraCoin, LiteCoin),
  Tickets_LiteCoin = new Pair (Tickets, LiteCoin),
  VeriCoin_LiteCoin = new Pair (VeriCoin, LiteCoin),
  VertCoin_LiteCoin = new Pair (VertCoin, LiteCoin),
  WorldCoin_LiteCoin = new Pair (WorldCoin, LiteCoin),
  X11Coin_LiteCoin = new Pair (X11Coin, LiteCoin),
  XenCoin_LiteCoin = new Pair (XenCoin, LiteCoin),
  PrimeCoin_LiteCoin = new Pair (PrimeCoin, LiteCoin),
  YaCoin_LiteCoin = new Pair (YaCoin, LiteCoin),
  ZeitCoin_LiteCoin = new Pair (ZeitCoin, LiteCoin),
  ZetaCoin_LiteCoin = new Pair (ZetaCoin, LiteCoin),
  OneCRedit_BitCoin = new Pair (OneCRedit, BitCoin),
  AppleByte_BitCoin = new Pair (AppleByte, BitCoin),
  Aiden_BitCoin = new Pair (Aiden, BitCoin),
  AEONCoin_BitCoin = new Pair (AEONCoin, BitCoin),
  Aerocoin_BitCoin = new Pair (Aerocoin, BitCoin),
  Axis_BitCoin = new Pair (Axis, BitCoin),
  BitBlock_BitCoin = new Pair (BitBlock, BitCoin),
  Boolberry_BitCoin = new Pair (Boolberry, BitCoin),
  BTCtalkcoin_BitCoin = new Pair (BTCtalkcoin, BitCoin),
  Bytecoin$Poloniex_BitCoin = new Pair (Bytecoin$Poloniex, BitCoin),
  BlackDragonCoin_BitCoin = new Pair (BlackDragonCoin, BitCoin),
  BellaCoin_BitCoin = new Pair (BellaCoin, BitCoin),
  Bitstar_BitCoin = new Pair (Bitstar, BitCoin),
  BonusCoin_BitCoin = new Pair (BonusCoin, BitCoin),
  Bones_BitCoin = new Pair (Bones, BitCoin),
  BoostCoin_BitCoin = new Pair (BoostCoin, BitCoin),
  Bitmark_BitCoin = new Pair (Bitmark, BitCoin),
  BurnerCoin_BitCoin = new Pair (BurnerCoin, BitCoin),
  CryptographicAnomaly_BitCoin = new Pair (CryptographicAnomaly, BitCoin),
  Chancecoin_BitCoin = new Pair (Chancecoin, BitCoin),
  CLAMS_BitCoin = new Pair (CLAMS, BitCoin),
  CNote_BitCoin = new Pair (CNote, BitCoin),
  Curecoin_BitCoin = new Pair (Curecoin, BitCoin),
  ConspiracyCoin_BitCoin = new Pair (ConspiracyCoin, BitCoin),
  CarpeDiemCoin_BitCoin = new Pair (CarpeDiemCoin, BitCoin),
  DistroCoin_BitCoin = new Pair (DistroCoin, BitCoin),
  DvoraKoin_BitCoin = new Pair (DvoraKoin, BitCoin),
  EBTcoin_BitCoin = new Pair (EBTcoin, BitCoin),
  ElectronicGulden_BitCoin = new Pair (ElectronicGulden, BitCoin),
  Entropycoin_BitCoin = new Pair (Entropycoin, BitCoin),
  Fantomcoin_BitCoin = new Pair (Fantomcoin, BitCoin),
  FVZCoin_BitCoin = new Pair (FVZCoin, BitCoin),
  Fuzon_BitCoin = new Pair (Fuzon, BitCoin),
  GlobalDenomination_BitCoin = new Pair (GlobalDenomination, BitCoin),
  Giarcoin_BitCoin = new Pair (Giarcoin, BitCoin),
  GameleagueCoin_BitCoin = new Pair (GameleagueCoin, BitCoin),
  GoldEagles_BitCoin = new Pair (GoldEagles, BitCoin),
  GROUPCoin_BitCoin = new Pair (GROUPCoin, BitCoin),
  Gridcoin_BitCoin = new Pair (Gridcoin, BitCoin),
  GroestlCoin_BitCoin = new Pair (GroestlCoin, BitCoin),
  Hirocoin_BitCoin = new Pair (Hirocoin, BitCoin),
  Hotcoin_BitCoin = new Pair (Hotcoin, BitCoin),
  jl777hodl_BitCoin = new Pair (jl777hodl, BitCoin),
  JackpotCoin_BitCoin = new Pair (JackpotCoin, BitCoin),
  Logicoin_BitCoin = new Pair (Logicoin, BitCoin),
  LeagueCoin_BitCoin = new Pair (LeagueCoin, BitCoin),
  MaidSafeCoin_BitCoin = new Pair (MaidSafeCoin, BitCoin),
  MastiffCoin_BitCoin = new Pair (MastiffCoin, BitCoin),
  MonetaVerde_BitCoin = new Pair (MonetaVerde, BitCoin),
  CryptoMETH_BitCoin = new Pair (CryptoMETH, BitCoin),
  MillionaireCoin_BitCoin = new Pair (MillionaireCoin, BitCoin),
  MemoryCoin_BitCoin = new Pair (MemoryCoin, BitCoin),
  MiningShares1GH_BitCoin = new Pair (MiningShares1GH, BitCoin),
  Monocle_BitCoin = new Pair (Monocle, BitCoin),
  microCoin_BitCoin = new Pair (microCoin, BitCoin),
  Marscoin_BitCoin = new Pair (Marscoin, BitCoin),
  Mastercoin_BitCoin = new Pair (Mastercoin, BitCoin),
  N5coin_BitCoin = new Pair (N5coin, BitCoin),
  NAS_BitCoin = new Pair (NAS, BitCoin),
  Navajo_BitCoin = new Pair (Navajo, BitCoin),
  Coin20_BitCoin = new Pair (Coin20, BitCoin),
  NextHorizon_BitCoin = new Pair (NextHorizon, BitCoin),
  Nanolite_BitCoin = new Pair (Nanolite, BitCoin),
  DNotes_BitCoin = new Pair (DNotes, BitCoin),
  NTX_BitCoin = new Pair (NTX, BitCoin),
  Pawncoin_BitCoin = new Pair (Pawncoin, BitCoin),
  Pinkcoin_BitCoin = new Pair (Pinkcoin, BitCoin),
  NewPiggycoin_BitCoin = new Pair (NewPiggycoin, BitCoin),
  ParallaxCoin_BitCoin = new Pair (ParallaxCoin, BitCoin),
  Premine_BitCoin = new Pair (Premine, BitCoin),
  ProsperCoin_BitCoin = new Pair (ProsperCoin, BitCoin),
  Particle_BitCoin = new Pair (Particle, BitCoin),
  Protoshares_BitCoin = new Pair (Protoshares, BitCoin),
  QubitCoin_BitCoin = new Pair (QubitCoin, BitCoin),
  Qibuck_BitCoin = new Pair (Qibuck, BitCoin),
  QuazarCoin_BitCoin = new Pair (QuazarCoin, BitCoin),
  Qora_BitCoin = new Pair (Qora, BitCoin),
  Rubycoin_BitCoin = new Pair (Rubycoin, BitCoin),
  Reddcoin$Poloniex_BitCoin = new Pair (Reddcoin$Poloniex, BitCoin),
  Riecoin_BitCoin = new Pair (Riecoin, BitCoin),
  ShibeCoin_BitCoin = new Pair (ShibeCoin, BitCoin),
  ShopX_BitCoin = new Pair (ShopX, BitCoin),
  Silkcoin$Poloniex_BitCoin = new Pair (Silkcoin$Poloniex, BitCoin),
  SocialCoin_BitCoin = new Pair (SocialCoin, BitCoin),
  SourceCoin_BitCoin = new Pair (SourceCoin, BitCoin),
  Stellar_BitCoin = new Pair (Stellar, BitCoin),
  Talkcoin_BitCoin = new Pair (Talkcoin, BitCoin),
  TrustPlus_BitCoin = new Pair (TrustPlus, BitCoin),
  USDE$Poloniex_BitCoin = new Pair (USDE$Poloniex, BitCoin),
  InsanityCoin_BitCoin = new Pair (InsanityCoin, BitCoin),
  APICoin_BitCoin = new Pair (APICoin, BitCoin),
  BitcoinPlus_BitCoin = new Pair (BitcoinPlus, BitCoin),
  XCurrency_BitCoin = new Pair (XCurrency, BitCoin),
  Counterparty_BitCoin = new Pair (Counterparty, BitCoin),
  duckNote_BitCoin = new Pair (duckNote, BitCoin),
  Honorcoin_BitCoin = new Pair (Honorcoin, BitCoin),
  Monero_BitCoin = new Pair (Monero, BitCoin),
  StabilityShares_BitCoin = new Pair (StabilityShares, BitCoin),
  YACCoin_BitCoin = new Pair (YACCoin, BitCoin),
  Yangcoin_BitCoin = new Pair (Yangcoin, BitCoin),
  Yincoin_BitCoin = new Pair (Yincoin, BitCoin),
  BlackCoin_Monero = new Pair (BlackCoin, Monero),
  Bytecoin$Poloniex_Monero = new Pair (Bytecoin$Poloniex, Monero),
  BitcoinDark_Monero = new Pair (BitcoinDark, Monero),
  CarpeDiemCoin_Monero = new Pair (CarpeDiemCoin, Monero),
  DarkCoin_Monero = new Pair (DarkCoin, Monero),
  InfiniteCoin_Monero = new Pair (InfiniteCoin, Monero),
  LiteCoin_Monero = new Pair (LiteCoin, Monero),
  MaidSafeCoin_Monero = new Pair (MaidSafeCoin, Monero),
  Nxt_Monero = new Pair (Nxt, Monero),
  Qora_Monero = new Pair (Qora, Monero),
  duckNote_Monero = new Pair (duckNote, Monero),
  SixtySixCoin_BitCoin = new Pair (SixtySixCoin, BitCoin),
  Aidbit_BitCoin = new Pair (Aidbit, BitCoin),
  Ascentcoin_BitCoin = new Pair (Ascentcoin, BitCoin),
  Buylatercoin_BitCoin = new Pair (Buylatercoin, BitCoin),
  Blazecoin_BitCoin = new Pair (Blazecoin, BitCoin),
  Bitmoney_BitCoin = new Pair (Bitmoney, BitCoin),
  Borgcoin_BitCoin = new Pair (Borgcoin, BitCoin),
  GlobalBoost_BitCoin = new Pair (GlobalBoost, BitCoin),
  Banksycoin_BitCoin = new Pair (Banksycoin, BitCoin),
  CaiShen_BitCoin = new Pair (CaiShen, BitCoin),
  CAPTcoin_BitCoin = new Pair (CAPTcoin, BitCoin),
  Chakracoin_BitCoin = new Pair (Chakracoin, BitCoin),
  Cloak_BitCoin = new Pair (Cloak, BitCoin),
  Compasscoin_BitCoin = new Pair (Compasscoin, BitCoin),
  Compucoin_BitCoin = new Pair (Compucoin, BitCoin),
  Credits_BitCoin = new Pair (Credits, BitCoin),
  EmbargoCoin_BitCoin = new Pair (EmbargoCoin, BitCoin),
  Fusecoin_BitCoin = new Pair (Fusecoin, BitCoin),
  GunCoin_BitCoin = new Pair (GunCoin, BitCoin),
  Hyperstake_BitCoin = new Pair (Hyperstake, BitCoin),
  ImperialcoinIMP_BitCoin = new Pair (ImperialcoinIMP, BitCoin),
  ImperialcoinIPC_BitCoin = new Pair (ImperialcoinIPC, BitCoin),
  Koolio_BitCoin = new Pair (Koolio, BitCoin),
  KryptKoin_BitCoin = new Pair (KryptKoin, BitCoin),
  LATIUM_BitCoin = new Pair (LATIUM, BitCoin),
  ElectronicLIRA_BitCoin = new Pair (ElectronicLIRA, BitCoin),
  Latinum_BitCoin = new Pair (Latinum, BitCoin),
  Multicoin_BitCoin = new Pair (Multicoin, BitCoin),
  PeoplesCurrency_BitCoin = new Pair (PeoplesCurrency, BitCoin),
  PayProCoin_BitCoin = new Pair (PayProCoin, BitCoin),
  PureCoin_BitCoin = new Pair (PureCoin, BitCoin),
  RobotSexNickels_BitCoin = new Pair (RobotSexNickels, BitCoin),
  Shadowcoin_BitCoin = new Pair (Shadowcoin, BitCoin),
  Shinycoin_BitCoin = new Pair (Shinycoin, BitCoin),
  Shibe_BitCoin = new Pair (Shibe, BitCoin),
  STLcoin_BitCoin = new Pair (STLcoin, BitCoin),
  VirtualminingCoin_BitCoin = new Pair (VirtualminingCoin, BitCoin),
  GoldReserve_BitCoin = new Pair (GoldReserve, BitCoin),
  YellowCoin_BitCoin = new Pair (YellowCoin, BitCoin),
  ActiveCoin_Dogecoin = new Pair (ActiveCoin, Dogecoin),
  Borgcoin_Dogecoin = new Pair (Borgcoin, Dogecoin),
  Bunnycoin_Dogecoin = new Pair (Bunnycoin, Dogecoin),
  CornerstoneCoin_Dogecoin = new Pair (CornerstoneCoin, Dogecoin),
  Dojecoin_Dogecoin = new Pair (Dojecoin, Dogecoin),
  Hobbitcoin_Dogecoin = new Pair (Hobbitcoin, Dogecoin),
  HTMLcoin_Dogecoin = new Pair (HTMLcoin, Dogecoin);

final List<Pair> AllPairs = <Pair>[
  BitCoin_USDollar,
  Dogecoin_USDollar,
  DarkCoin_USDollar,
  FeatherCoin_USDollar,
  LiteCoin_USDollar,
  ReddCoin$Cryptsy_USDollar,
  FourtyTwoCoin_BitCoin,
  AsiaCoin_BitCoin,
  Aegis_BitCoin,
  AlphaCoin_BitCoin,
  AlienCoin_BitCoin,
  AmericanCoin_BitCoin,
  AnonCoin_BitCoin,
  ApexCoin_BitCoin,
  Argentum_BitCoin,
  AuroraCoin_BitCoin,
  BlackCoin_BitCoin,
  BattleCoin_BitCoin,
  Benjamins_BitCoin,
  Betacoin_BitCoin,
  BlueCoin_BitCoin,
  BBQCoin_BitCoin,
  BitBar_BitCoin,
  BitcoinDark_BitCoin,
  ByteCoin$Cryptsy_BitCoin,
  BitGem_BitCoin,
  CryptoBuck_BitCoin,
  CACHeCoin_BitCoin,
  CAIx_BitCoin,
  BottleCaps_BitCoin,
  CashCoin_BitCoin,
  CatCoin_BitCoin,
  CryptogenicBullion_BitCoin,
  CinniCoin_BitCoin,
  CloakCoin_BitCoin,
  CopperLark_BitCoin,
  Cosmoscoin_BitCoin,
  CHNCoin_BitCoin,
  ConcealCoin_BitCoin,
  CommunityCoin_BitCoin,
  CoolCoin_BitCoin,
  CraftCoin_BitCoin,
  CryptCoin_BitCoin,
  CasinoCoin_BitCoin,
  eMark_BitCoin,
  Digibyte_BitCoin,
  DigitalCoin_BitCoin,
  Diamond_BitCoin,
  Dogecoin_BitCoin,
  DarkCoin_BitCoin,
  DarkCash_BitCoin,
  DevCoin_BitCoin,
  EarthCoin_BitCoin,
  ElaCoin_BitCoin,
  Einsteinium_BitCoin,
  Emerald_BitCoin,
  ExeCoin_BitCoin,
  EZCoin_BitCoin,
  FireflyCoin_BitCoin,
  FlutterCoin_BitCoin,
  FractalCoin_BitCoin,
  FreiCoin_BitCoin,
  Franko_BitCoin,
  FastCoin_BitCoin,
  FeatherCoin_BitCoin,
  GrandCoin_BitCoin,
  Globalcoin_BitCoin,
  GoldCoin_BitCoin,
  Galaxycoin_BitCoin,
  GlyphCoin_BitCoin,
  GuerillaCoin_BitCoin,
  HoboNickels_BitCoin,
  HunterCoin_BitCoin,
  HeavyCoin_BitCoin,
  IcebergCoin_BitCoin,
  InfiniteCoin_BitCoin,
  IOCoin_BitCoin,
  IXCoin_BitCoin,
  JunkCoin_BitCoin,
  JudgeCoin_BitCoin,
  KlondikeCoin_BitCoin,
  KeyCoin_BitCoin,
  KrugerCoin_BitCoin,
  LegendaryCoin_BitCoin,
  Lucky7Coin_BitCoin,
  LuckyCoin_BitCoin,
  LiteBar_BitCoin,
  LiteCoin_BitCoin,
  LiteCoinX_BitCoin,
  LycanCoin_BitCoin,
  MaxCoin_BitCoin,
  MegaCoin_BitCoin,
  Minerals_BitCoin,
  MintCoin_BitCoin,
  MiningContract1_BitCoin,
  MiningContract2_BitCoin,
  MinCoin_BitCoin,
  MurrayCoin_BitCoin,
  MyriadCoin_BitCoin,
  MazaCoin_BitCoin,
  NanoToken_BitCoin,
  NautilusCoin_BitCoin,
  NavajoCoin_BitCoin,
  Nibble_BitCoin,
  NeoCoin_BitCoin,
  Netcoin_BitCoin,
  NameCoin_BitCoin,
  NobleCoin_BitCoin,
  NoirBits_BitCoin,
  NoirShares_BitCoin,
  NovaCoin_BitCoin,
  Nxt_BitCoin,
  NyanCoin_BitCoin,
  Orbitcoin_BitCoin,
  OpenSourceCoin_BitCoin,
  PhilosopherStone_BitCoin,
  CryptsyPoints_BitCoin,
  PotCoin_BitCoin,
  Peercoin_BitCoin,
  PseudoCoin_BitCoin,
  BitsharesPTS_BitCoin,
  PhoenixCoin_BitCoin,
  PayCoin_BitCoin,
  Quark_BitCoin,
  ReddCoin$Cryptsy_BitCoin,
  RonPaulCoin_BitCoin,
  RotoCoin_BitCoin,
  RoyalCoin_BitCoin,
  Razor_BitCoin,
  SaturnCoinV2_BitCoin,
  StableCoin_BitCoin,
  SilkCoin$Cryptsy_BitCoin,
  SaffronCoin_BitCoin,
  ShieldCoin_BitCoin,
  SmartCoin_BitCoin,
  SpainCoin_BitCoin,
  Spots_BitCoin,
  SecureCoin_BitCoin,
  StarCoin_BitCoin,
  SuperCoin_BitCoin,
  SexCoin_BitCoin,
  Sync_BitCoin,
  TagCoin_BitCoin,
  TakCoin_BitCoin,
  TekCoin_BitCoin,
  TeslaCoin_BitCoin,
  TigerCoin_BitCoin,
  TorCoin_BitCoin,
  TerraCoin_BitCoin,
  UnbreakableCoin_BitCoin,
  Unobtanium_BitCoin,
  URO_BitCoin,
  USDe$Cryptsy_BitCoin,
  UltraCoin_BitCoin,
  ViaCoin_BitCoin,
  VootCoin_BitCoin,
  VeriCoin_BitCoin,
  VertCoin_BitCoin,
  WhiteCoin_BitCoin,
  WorldCoin_BitCoin,
  X11Coin_BitCoin,
  JouleCoin_BitCoin,
  LibertyCoin_BitCoin,
  PrimeCoin_BitCoin,
  XXXCoin_BitCoin,
  YaCoin_BitCoin,
  YBCoin_BitCoin,
  ZcCoin_BitCoin,
  ZedCoin_BitCoin,
  ZetaCoin_BitCoin,
  AndroidsTokensV2_LiteCoin,
  AnonCoin_LiteCoin,
  AsicCoin_LiteCoin,
  AuroraCoin_LiteCoin,
  BatCoin_LiteCoin,
  BlackCoin_LiteCoin,
  CryptogenicBullion_LiteCoin,
  CloakCoin_LiteCoin,
  CHNCoin_LiteCoin,
  ColossusCoin_LiteCoin,
  CopperBars_LiteCoin,
  CryptCoin_LiteCoin,
  Continuumcoin_LiteCoin,
  Doubloons_LiteCoin,
  DigitalCoin_LiteCoin,
  DimeCoin_LiteCoin,
  DamaCoin_LiteCoin,
  Dogecoin_LiteCoin,
  DarkCoin_LiteCoin,
  DevCoin_LiteCoin,
  EarthCoin_LiteCoin,
  ElephantCoin_LiteCoin,
  EZCoin_LiteCoin,
  FlappyCoin_LiteCoin,
  FlorinCoin_LiteCoin,
  Franko_LiteCoin,
  FastCoin_LiteCoin,
  FeatherCoin_LiteCoin,
  GoldCoin_LiteCoin,
  GlyphCoin_LiteCoin,
  GameCoin_LiteCoin,
  GuerillaCoin_LiteCoin,
  InfiniteCoin_LiteCoin,
  KarmaCoin_LiteCoin,
  LeafCoin_LiteCoin,
  LottoCoin_LiteCoin,
  LiteCoinX_LiteCoin,
  MaxCoin_LiteCoin,
  MegaCoin_LiteCoin,
  MemeCoin_LiteCoin,
  KittehCoin_LiteCoin,
  MoonCoin_LiteCoin,
  MasterCoinHydro_LiteCoin,
  Netcoin_LiteCoin,
  Nxt_LiteCoin,
  NyanCoin_LiteCoin,
  Peercoin_LiteCoin,
  PhoenixCoin_LiteCoin,
  Quark_LiteCoin,
  RabbitCoin_LiteCoin,
  ReddCoin$Cryptsy_LiteCoin,
  RedCoin_LiteCoin,
  Razor_LiteCoin,
  StableCoin_LiteCoin,
  SuperCoin_LiteCoin,
  SexCoin_LiteCoin,
  TeslaCoin_LiteCoin,
  FedoraCoin_LiteCoin,
  Tickets_LiteCoin,
  VeriCoin_LiteCoin,
  VertCoin_LiteCoin,
  WorldCoin_LiteCoin,
  X11Coin_LiteCoin,
  XenCoin_LiteCoin,
  PrimeCoin_LiteCoin,
  YaCoin_LiteCoin,
  ZeitCoin_LiteCoin,
  ZetaCoin_LiteCoin,
  OneCRedit_BitCoin,
  AppleByte_BitCoin,
  Aiden_BitCoin,
  AEONCoin_BitCoin,
  Aerocoin_BitCoin,
  Axis_BitCoin,
  BitBlock_BitCoin,
  Boolberry_BitCoin,
  BTCtalkcoin_BitCoin,
  Bytecoin$Poloniex_BitCoin,
  BlackDragonCoin_BitCoin,
  BellaCoin_BitCoin,
  Bitstar_BitCoin,
  BonusCoin_BitCoin,
  Bones_BitCoin,
  BoostCoin_BitCoin,
  Bitmark_BitCoin,
  BurnerCoin_BitCoin,
  CryptographicAnomaly_BitCoin,
  Chancecoin_BitCoin,
  CLAMS_BitCoin,
  CNote_BitCoin,
  Curecoin_BitCoin,
  ConspiracyCoin_BitCoin,
  CarpeDiemCoin_BitCoin,
  DistroCoin_BitCoin,
  DvoraKoin_BitCoin,
  EBTcoin_BitCoin,
  ElectronicGulden_BitCoin,
  Entropycoin_BitCoin,
  Fantomcoin_BitCoin,
  FVZCoin_BitCoin,
  Fuzon_BitCoin,
  GlobalDenomination_BitCoin,
  Giarcoin_BitCoin,
  GameleagueCoin_BitCoin,
  GoldEagles_BitCoin,
  GROUPCoin_BitCoin,
  Gridcoin_BitCoin,
  GroestlCoin_BitCoin,
  Hirocoin_BitCoin,
  Hotcoin_BitCoin,
  jl777hodl_BitCoin,
  JackpotCoin_BitCoin,
  Logicoin_BitCoin,
  LeagueCoin_BitCoin,
  MaidSafeCoin_BitCoin,
  MastiffCoin_BitCoin,
  MonetaVerde_BitCoin,
  CryptoMETH_BitCoin,
  MillionaireCoin_BitCoin,
  MemoryCoin_BitCoin,
  MiningShares1GH_BitCoin,
  Monocle_BitCoin,
  microCoin_BitCoin,
  Marscoin_BitCoin,
  Mastercoin_BitCoin,
  N5coin_BitCoin,
  NAS_BitCoin,
  Navajo_BitCoin,
  Coin20_BitCoin,
  NextHorizon_BitCoin,
  Nanolite_BitCoin,
  DNotes_BitCoin,
  NTX_BitCoin,
  Pawncoin_BitCoin,
  Pinkcoin_BitCoin,
  NewPiggycoin_BitCoin,
  ParallaxCoin_BitCoin,
  Premine_BitCoin,
  ProsperCoin_BitCoin,
  Particle_BitCoin,
  Protoshares_BitCoin,
  QubitCoin_BitCoin,
  Qibuck_BitCoin,
  QuazarCoin_BitCoin,
  Qora_BitCoin,
  Rubycoin_BitCoin,
  Reddcoin$Poloniex_BitCoin,
  Riecoin_BitCoin,
  ShibeCoin_BitCoin,
  ShopX_BitCoin,
  Silkcoin$Poloniex_BitCoin,
  SocialCoin_BitCoin,
  SourceCoin_BitCoin,
  Stellar_BitCoin,
  Talkcoin_BitCoin,
  TrustPlus_BitCoin,
  USDE$Poloniex_BitCoin,
  InsanityCoin_BitCoin,
  APICoin_BitCoin,
  BitcoinPlus_BitCoin,
  XCurrency_BitCoin,
  Counterparty_BitCoin,
  duckNote_BitCoin,
  Honorcoin_BitCoin,
  Monero_BitCoin,
  StabilityShares_BitCoin,
  YACCoin_BitCoin,
  Yangcoin_BitCoin,
  Yincoin_BitCoin,
  BlackCoin_Monero,
  Bytecoin$Poloniex_Monero,
  BitcoinDark_Monero,
  CarpeDiemCoin_Monero,
  DarkCoin_Monero,
  InfiniteCoin_Monero,
  LiteCoin_Monero,
  MaidSafeCoin_Monero,
  Nxt_Monero,
  Qora_Monero,
  duckNote_Monero,
  SixtySixCoin_BitCoin,
  Aidbit_BitCoin,
  Ascentcoin_BitCoin,
  Buylatercoin_BitCoin,
  Blazecoin_BitCoin,
  Bitmoney_BitCoin,
  Borgcoin_BitCoin,
  GlobalBoost_BitCoin,
  Banksycoin_BitCoin,
  CaiShen_BitCoin,
  CAPTcoin_BitCoin,
  Chakracoin_BitCoin,
  Cloak_BitCoin,
  Compasscoin_BitCoin,
  Compucoin_BitCoin,
  Credits_BitCoin,
  EmbargoCoin_BitCoin,
  Fusecoin_BitCoin,
  GunCoin_BitCoin,
  Hyperstake_BitCoin,
  ImperialcoinIMP_BitCoin,
  ImperialcoinIPC_BitCoin,
  Koolio_BitCoin,
  KryptKoin_BitCoin,
  LATIUM_BitCoin,
  ElectronicLIRA_BitCoin,
  Latinum_BitCoin,
  Multicoin_BitCoin,
  PeoplesCurrency_BitCoin,
  PayProCoin_BitCoin,
  PureCoin_BitCoin,
  RobotSexNickels_BitCoin,
  Shadowcoin_BitCoin,
  Shinycoin_BitCoin,
  Shibe_BitCoin,
  STLcoin_BitCoin,
  VirtualminingCoin_BitCoin,
  GoldReserve_BitCoin,
  YellowCoin_BitCoin,
  ActiveCoin_Dogecoin,
  Borgcoin_Dogecoin,
  Bunnycoin_Dogecoin,
  CornerstoneCoin_Dogecoin,
  Dojecoin_Dogecoin,
  Hobbitcoin_Dogecoin,
  HTMLcoin_Dogecoin
];
